/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

#line 43 "/usr/include/machine/int_types.h"
typedef signed char __int8_t;
#line 44 "/usr/include/machine/int_types.h"
typedef unsigned char __uint8_t;
#line 45 "/usr/include/machine/int_types.h"
typedef short __int16_t;
#line 46 "/usr/include/machine/int_types.h"
typedef unsigned short __uint16_t;
#line 47 "/usr/include/machine/int_types.h"
typedef int __int32_t;
#line 48 "/usr/include/machine/int_types.h"
typedef unsigned int __uint32_t;
#line 54 "/usr/include/machine/int_types.h"
typedef long long __int64_t;
#line 56 "/usr/include/machine/int_types.h"
typedef unsigned long long __uint64_t;
#line 63 "/usr/include/machine/int_types.h"
typedef int __intptr_t;
#line 64 "/usr/include/machine/int_types.h"
typedef unsigned int __uintptr_t;
#line 44 "/usr/include/sys/ansi.h"
typedef char *__caddr_t;
#line 45 "/usr/include/sys/ansi.h"
typedef __uint32_t __gid_t;
#line 46 "/usr/include/sys/ansi.h"
typedef __uint32_t __in_addr_t;
#line 47 "/usr/include/sys/ansi.h"
typedef __uint16_t __in_port_t;
#line 48 "/usr/include/sys/ansi.h"
typedef __uint32_t __mode_t;
#line 49 "/usr/include/sys/ansi.h"
typedef __int64_t __off_t;
#line 50 "/usr/include/sys/ansi.h"
typedef __int32_t __pid_t;
#line 51 "/usr/include/sys/ansi.h"
typedef __uint8_t __sa_family_t;
#line 52 "/usr/include/sys/ansi.h"
typedef unsigned int __socklen_t;
#line 53 "/usr/include/sys/ansi.h"
typedef __uint32_t __uid_t;
#line 92 "/usr/include/machine/ansi.h"
union __anonunion___mbstate_t_1 {
   char __mbstate8[128] ;
   __int64_t __mbstateL ;
};
#line 92 "/usr/include/machine/ansi.h"
typedef union __anonunion___mbstate_t_1 __mbstate_t;
#line 47 "/usr/include/stdio.h"
typedef unsigned int size_t;
#line 59 "/usr/include/stdio.h"
typedef __off_t fpos_t;
#line 75 "/usr/include/stdio.h"
struct __sbuf {
   unsigned char *_base ;
   int _size ;
};
#line 106 "/usr/include/stdio.h"
struct __sFILE {
   unsigned char *_p ;
   int _r ;
   int _w ;
   short _flags ;
   short _file ;
   struct __sbuf _bf ;
   int _lbfsize ;
   void *_cookie ;
   int (*_close)(void * ) ;
   int (*_read)(void * , char * , int  ) ;
   fpos_t (*_seek)(void * , fpos_t  , int  ) ;
   int (*_write)(void * , char const   * , int  ) ;
   struct __sbuf _ext ;
   unsigned char *_up ;
   int _ur ;
   unsigned char _ubuf[3] ;
   unsigned char _nbuf[1] ;
   struct __sbuf _lb ;
   int _blksize ;
   fpos_t _offset ;
};
#line 106 "/usr/include/stdio.h"
typedef struct __sFILE FILE;
#line 344 "/usr/include/stdio.h"
typedef __off_t off_t;
#line 49 "/usr/include/machine/types.h"
typedef unsigned long paddr_t;
#line 50 "/usr/include/machine/types.h"
typedef unsigned long psize_t;
#line 51 "/usr/include/machine/types.h"
typedef unsigned long vaddr_t;
#line 52 "/usr/include/machine/types.h"
typedef unsigned long vsize_t;
#line 55 "/usr/include/machine/types.h"
typedef int pmc_evid_t;
#line 56 "/usr/include/machine/types.h"
typedef __uint64_t pmc_ctr_t;
#line 57 "/usr/include/machine/types.h"
typedef int register_t;
#line 59 "/usr/include/machine/types.h"
typedef int volatile   __cpu_simple_lock_t;
#line 54 "/usr/include/sys/types.h"
typedef __int8_t int8_t;
#line 59 "/usr/include/sys/types.h"
typedef __uint8_t uint8_t;
#line 64 "/usr/include/sys/types.h"
typedef __int16_t int16_t;
#line 69 "/usr/include/sys/types.h"
typedef __uint16_t uint16_t;
#line 74 "/usr/include/sys/types.h"
typedef __int32_t int32_t;
#line 79 "/usr/include/sys/types.h"
typedef __uint32_t uint32_t;
#line 84 "/usr/include/sys/types.h"
typedef __int64_t int64_t;
#line 89 "/usr/include/sys/types.h"
typedef __uint64_t uint64_t;
#line 93 "/usr/include/sys/types.h"
typedef __uint8_t u_int8_t;
#line 94 "/usr/include/sys/types.h"
typedef __uint16_t u_int16_t;
#line 95 "/usr/include/sys/types.h"
typedef __uint32_t u_int32_t;
#line 96 "/usr/include/sys/types.h"
typedef __uint64_t u_int64_t;
#line 82 "/usr/include/sys/endian.h"
typedef __in_addr_t in_addr_t;
#line 87 "/usr/include/sys/endian.h"
typedef __in_port_t in_port_t;
#line 101 "/usr/include/sys/types.h"
typedef unsigned char u_char;
#line 102 "/usr/include/sys/types.h"
typedef unsigned short u_short;
#line 103 "/usr/include/sys/types.h"
typedef unsigned int u_int;
#line 104 "/usr/include/sys/types.h"
typedef unsigned long u_long;
#line 106 "/usr/include/sys/types.h"
typedef unsigned char unchar;
#line 107 "/usr/include/sys/types.h"
typedef unsigned short ushort;
#line 108 "/usr/include/sys/types.h"
typedef unsigned int uint;
#line 109 "/usr/include/sys/types.h"
typedef unsigned long ulong;
#line 111 "/usr/include/sys/types.h"
typedef u_long cpuid_t;
#line 114 "/usr/include/sys/types.h"
typedef __uint64_t u_quad_t;
#line 115 "/usr/include/sys/types.h"
typedef __int64_t quad_t;
#line 116 "/usr/include/sys/types.h"
typedef quad_t *qaddr_t;
#line 128 "/usr/include/sys/types.h"
typedef __int64_t longlong_t;
#line 129 "/usr/include/sys/types.h"
typedef __uint64_t u_longlong_t;
#line 131 "/usr/include/sys/types.h"
typedef __int64_t blkcnt_t;
#line 132 "/usr/include/sys/types.h"
typedef __uint32_t blksize_t;
#line 135 "/usr/include/sys/types.h"
typedef __caddr_t caddr_t;
#line 143 "/usr/include/sys/types.h"
typedef __int64_t daddr_t;
#line 146 "/usr/include/sys/types.h"
typedef __uint32_t dev_t;
#line 147 "/usr/include/sys/types.h"
typedef __uint32_t fixpt_t;
#line 150 "/usr/include/sys/types.h"
typedef __gid_t gid_t;
#line 154 "/usr/include/sys/types.h"
typedef __uint32_t id_t;
#line 155 "/usr/include/sys/types.h"
typedef __uint32_t ino_t;
#line 156 "/usr/include/sys/types.h"
typedef long key_t;
#line 159 "/usr/include/sys/types.h"
typedef __mode_t mode_t;
#line 163 "/usr/include/sys/types.h"
typedef __uint32_t nlink_t;
#line 171 "/usr/include/sys/types.h"
typedef __pid_t pid_t;
#line 174 "/usr/include/sys/types.h"
typedef __int32_t lwpid_t;
#line 175 "/usr/include/sys/types.h"
typedef quad_t rlim_t;
#line 176 "/usr/include/sys/types.h"
typedef __int32_t segsz_t;
#line 177 "/usr/include/sys/types.h"
typedef __int32_t swblk_t;
#line 180 "/usr/include/sys/types.h"
typedef __uid_t uid_t;
#line 184 "/usr/include/sys/types.h"
typedef __int32_t dtime_t;
#line 242 "/usr/include/sys/types.h"
typedef unsigned long clock_t;
#line 253 "/usr/include/sys/types.h"
typedef int ssize_t;
#line 258 "/usr/include/sys/types.h"
typedef long time_t;
#line 263 "/usr/include/sys/types.h"
typedef int clockid_t;
#line 268 "/usr/include/sys/types.h"
typedef int timer_t;
#line 273 "/usr/include/sys/types.h"
typedef int suseconds_t;
#line 278 "/usr/include/sys/types.h"
typedef unsigned int useconds_t;
#line 290 "/usr/include/sys/types.h"
typedef __int32_t __fd_mask;
#line 309 "/usr/include/sys/types.h"
struct fd_set {
   __fd_mask fds_bits[(256U + (sizeof(__fd_mask ) * 8U - 1U)) / (sizeof(__fd_mask ) * 8U)] ;
};
#line 309 "/usr/include/sys/types.h"
typedef struct fd_set fd_set;
#line 46 "/usr/include/pthread_types.h"
typedef __cpu_simple_lock_t pthread_spin_t;
#line 57
struct __pthread_st;
#line 57 "/usr/include/pthread_types.h"
struct pthread_queue_t {
   struct __pthread_st *ptqh_first ;
   struct __pthread_st **ptqh_last ;
};
#line 59
struct __pthread_st;
#line 60
struct __pthread_attr_st;
#line 60
struct __pthread_attr_st;
#line 61
struct __pthread_mutex_st;
#line 61
struct __pthread_mutex_st;
#line 62
struct __pthread_mutexattr_st;
#line 62
struct __pthread_mutexattr_st;
#line 63
struct __pthread_cond_st;
#line 63
struct __pthread_cond_st;
#line 64
struct __pthread_condattr_st;
#line 64
struct __pthread_condattr_st;
#line 65
struct __pthread_spin_st;
#line 65
struct __pthread_spin_st;
#line 66
struct __pthread_rwlock_st;
#line 66
struct __pthread_rwlock_st;
#line 67
struct __pthread_rwlockattr_st;
#line 67
struct __pthread_rwlockattr_st;
#line 68
struct __pthread_barrier_st;
#line 68
struct __pthread_barrier_st;
#line 69
struct __pthread_barrierattr_st;
#line 69
struct __pthread_barrierattr_st;
#line 71 "/usr/include/pthread_types.h"
typedef struct __pthread_st *pthread_t;
#line 72 "/usr/include/pthread_types.h"
typedef struct __pthread_attr_st pthread_attr_t;
#line 73 "/usr/include/pthread_types.h"
typedef struct __pthread_mutex_st pthread_mutex_t;
#line 74 "/usr/include/pthread_types.h"
typedef struct __pthread_mutexattr_st pthread_mutexattr_t;
#line 75 "/usr/include/pthread_types.h"
typedef struct __pthread_cond_st pthread_cond_t;
#line 76 "/usr/include/pthread_types.h"
typedef struct __pthread_condattr_st pthread_condattr_t;
#line 77
struct __pthread_once_st;
#line 77 "/usr/include/pthread_types.h"
typedef struct __pthread_once_st pthread_once_t;
#line 78
struct __pthread_spinlock_st;
#line 78 "/usr/include/pthread_types.h"
typedef struct __pthread_spinlock_st pthread_spinlock_t;
#line 79 "/usr/include/pthread_types.h"
typedef struct __pthread_rwlock_st pthread_rwlock_t;
#line 80 "/usr/include/pthread_types.h"
typedef struct __pthread_rwlockattr_st pthread_rwlockattr_t;
#line 81 "/usr/include/pthread_types.h"
typedef struct __pthread_barrier_st pthread_barrier_t;
#line 82 "/usr/include/pthread_types.h"
typedef struct __pthread_barrierattr_st pthread_barrierattr_t;
#line 83 "/usr/include/pthread_types.h"
typedef int pthread_key_t;
#line 85 "/usr/include/pthread_types.h"
struct __pthread_attr_st {
   unsigned int pta_magic ;
   int pta_flags ;
   void *pta_private ;
};
#line 92 "/usr/include/pthread_types.h"
struct __pthread_mutex_st {
   unsigned int ptm_magic ;
   pthread_spin_t ptm_lock ;
   pthread_spin_t ptm_interlock ;
   pthread_t ptm_owner ;
   struct pthread_queue_t ptm_blocked ;
   void *ptm_private ;
};
#line 123 "/usr/include/pthread_types.h"
struct __pthread_mutexattr_st {
   unsigned int ptma_magic ;
   void *ptma_private ;
};
#line 132 "/usr/include/pthread_types.h"
struct __pthread_cond_st {
   unsigned int ptc_magic ;
   pthread_spin_t ptc_lock ;
   struct pthread_queue_t ptc_waiters ;
   pthread_mutex_t *ptc_mutex ;
   void *ptc_private ;
};
#line 153 "/usr/include/pthread_types.h"
struct __pthread_condattr_st {
   unsigned int ptca_magic ;
   void *ptca_private ;
};
#line 161 "/usr/include/pthread_types.h"
struct __pthread_once_st {
   pthread_mutex_t pto_mutex ;
   int pto_done ;
};
#line 168 "/usr/include/pthread_types.h"
struct __pthread_spinlock_st {
   unsigned int pts_magic ;
   pthread_spin_t pts_spin ;
   int pts_flags ;
};
#line 184 "/usr/include/pthread_types.h"
struct __pthread_rwlock_st {
   unsigned int ptr_magic ;
   pthread_spin_t ptr_interlock ;
   struct pthread_queue_t ptr_rblocked ;
   struct pthread_queue_t ptr_wblocked ;
   unsigned int ptr_nreaders ;
   pthread_t ptr_writer ;
   void *ptr_private ;
};
#line 209 "/usr/include/pthread_types.h"
struct __pthread_rwlockattr_st {
   unsigned int ptra_magic ;
   void *ptra_private ;
};
#line 217 "/usr/include/pthread_types.h"
struct __pthread_barrier_st {
   unsigned int ptb_magic ;
   pthread_spin_t ptb_lock ;
   struct pthread_queue_t ptb_waiters ;
   unsigned int ptb_initcount ;
   unsigned int ptb_curcount ;
   unsigned int ptb_generation ;
   void *ptb_private ;
};
#line 234 "/usr/include/pthread_types.h"
struct __pthread_barrierattr_st {
   unsigned int ptba_magic ;
   void *ptba_private ;
};
#line 52 "/usr/include/stdlib.h"
typedef int wchar_t;
#line 56 "/usr/include/stdlib.h"
struct __anonstruct_div_t_2 {
   int quot ;
   int rem ;
};
#line 56 "/usr/include/stdlib.h"
typedef struct __anonstruct_div_t_2 div_t;
#line 61 "/usr/include/stdlib.h"
struct __anonstruct_ldiv_t_3 {
   long quot ;
   long rem ;
};
#line 61 "/usr/include/stdlib.h"
typedef struct __anonstruct_ldiv_t_3 ldiv_t;
#line 69 "/usr/include/stdlib.h"
struct __anonstruct_lldiv_t_4 {
   long long quot ;
   long long rem ;
};
#line 69 "/usr/include/stdlib.h"
typedef struct __anonstruct_lldiv_t_4 lldiv_t;
#line 78 "/usr/include/stdlib.h"
struct __anonstruct_qdiv_t_5 {
   quad_t quot ;
   quad_t rem ;
};
#line 78 "/usr/include/stdlib.h"
typedef struct __anonstruct_qdiv_t_5 qdiv_t;
#line 233 "/usr/include/unistd.h"
typedef __intptr_t intptr_t;
#line 285
struct timeval;
#line 285
struct timeval;
#line 75 "/usr/include/time.h"
struct tm {
   int tm_sec ;
   int tm_min ;
   int tm_hour ;
   int tm_mday ;
   int tm_mon ;
   int tm_year ;
   int tm_wday ;
   int tm_yday ;
   int tm_isdst ;
   long tm_gmtoff ;
   char *tm_zone ;
};
#line 49 "/usr/include/sys/time.h"
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
#line 57 "/usr/include/sys/time.h"
struct timespec {
   time_t tv_sec ;
   long tv_nsec ;
};
#line 75 "/usr/include/sys/time.h"
struct timezone {
   int tz_minuteswest ;
   int tz_dsttime ;
};
#line 140 "/usr/include/sys/time.h"
struct itimerval {
   struct timeval it_interval ;
   struct timeval it_value ;
};
#line 149 "/usr/include/sys/time.h"
struct itimerspec {
   struct timespec it_interval ;
   struct timespec it_value ;
};
#line 157 "/usr/include/sys/time.h"
struct clockinfo {
   int hz ;
   int tick ;
   int tickadj ;
   int stathz ;
   int profhz ;
};
#line 136 "/usr/include/time.h"
struct sigevent;
#line 136
struct sigevent;
#line 137
struct itimerspec;
#line 85 "/usr/include/sys/sched.h"
struct sched_param {
   int sched_priority ;
};
#line 111
struct lwp;
#line 111 "/usr/include/sys/sched.h"
struct slpque {
   struct lwp *sq_head ;
   struct lwp **sq_tailp ;
};
#line 126 "/usr/include/sys/sched.h"
struct prochd {
   struct lwp *ph_link ;
   struct lwp *ph_rlink ;
};
#line 146 "/usr/include/sys/sched.h"
struct schedstate_percpu {
   struct timeval spc_runtime ;
   int volatile   spc_flags ;
   u_int spc_schedticks ;
   u_int64_t spc_cp_time[5] ;
   u_char spc_curpriority ;
   int spc_rrticks ;
   int spc_pscnt ;
   int spc_psdiv ;
};
#line 126 "/usr/include/pthread.h"
struct pthread_cleanup_store {
   void *pad[4] ;
};
#line 53 "/usr/include/setjmp.h"
typedef long sigjmp_buf[14];
#line 56 "/usr/include/setjmp.h"
typedef long jmp_buf[13];
#line 90 "/usr/include/sys/stdint.h"
typedef __uintptr_t uintptr_t;
#line 48 "/usr/include/machine/int_mwgwtypes.h"
typedef signed char int_least8_t;
#line 49 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned char uint_least8_t;
#line 50 "/usr/include/machine/int_mwgwtypes.h"
typedef short int_least16_t;
#line 51 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned short uint_least16_t;
#line 52 "/usr/include/machine/int_mwgwtypes.h"
typedef int int_least32_t;
#line 53 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned int uint_least32_t;
#line 59 "/usr/include/machine/int_mwgwtypes.h"
typedef long long int_least64_t;
#line 61 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned long long uint_least64_t;
#line 66 "/usr/include/machine/int_mwgwtypes.h"
typedef signed char int_fast8_t;
#line 67 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned char uint_fast8_t;
#line 68 "/usr/include/machine/int_mwgwtypes.h"
typedef int int_fast16_t;
#line 69 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned int uint_fast16_t;
#line 70 "/usr/include/machine/int_mwgwtypes.h"
typedef int int_fast32_t;
#line 71 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned int uint_fast32_t;
#line 77 "/usr/include/machine/int_mwgwtypes.h"
typedef long long int_fast64_t;
#line 79 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned long long uint_fast64_t;
#line 89 "/usr/include/machine/int_mwgwtypes.h"
typedef long long intmax_t;
#line 91 "/usr/include/machine/int_mwgwtypes.h"
typedef unsigned long long uintmax_t;
#line 81 "/usr/include/wchar.h"
typedef __mbstate_t mbstate_t;
#line 86 "/usr/include/wchar.h"
typedef int wint_t;
#line 39 "/usr/include/stddef.h"
typedef int ptrdiff_t;
#line 27 "tl2/tmalloc.h"
struct tmalloc {
   long size ;
   long capacity ;
   void **elements ;
};
#line 27 "tl2/tmalloc.h"
typedef struct tmalloc tmalloc_t;
#line 41 "tl2/tl2.h"
typedef int BitMap;
#line 42 "tl2/tl2.h"
typedef __uintptr_t vwLock;
#line 43 "tl2/tl2.h"
typedef unsigned char byte;
#line 46
struct _Thread;
#line 46 "tl2/tl2.h"
struct _AVPair {
   struct _AVPair *Next ;
   struct _AVPair *Prev ;
   __intptr_t volatile   *Addr ;
   __intptr_t Valu ;
   vwLock volatile   *LockFor ;
   vwLock rdv ;
   byte Held ;
   struct _Thread *Owner ;
   long Ordinal ;
};
#line 46 "tl2/tl2.h"
typedef struct _AVPair AVPair;
#line 58 "tl2/tl2.h"
struct _Log {
   AVPair *List ;
   AVPair *put ;
   AVPair *tail ;
   long ovf ;
   BitMap BloomFilter ;
};
#line 58 "tl2/tl2.h"
typedef struct _Log Log;
#line 77 "tl2/tl2.h"
struct _Thread {
   long UniqID ;
   long volatile   Mode ;
   long volatile   HoldsLocks ;
   long volatile   Retries ;
   vwLock volatile   rv ;
   vwLock wv ;
   vwLock abv ;
   int *ROFlag ;
   int IsRO ;
   long Starts ;
   long Aborts ;
   unsigned long long rng ;
   unsigned long long xorrng[1] ;
   void *memCache ;
   tmalloc_t *allocPtr ;
   tmalloc_t *freePtr ;
   Log rdSet ;
   Log wrSet ;
   Log LocalUndo ;
   sigjmp_buf *envPtr ;
};
#line 77 "tl2/tl2.h"
typedef struct _Thread Thread;
#line 14 "al.h"
struct __anonstruct_profile_t_6 {
   char const   *name ;
   __intptr_t volatile   lockHeld ;
   __intptr_t volatile   threadsWaiting ;
   __intptr_t volatile   tries ;
   __intptr_t volatile   commit ;
   __intptr_t volatile   invokeInLockMode ;
   __intptr_t volatile   waitLock ;
};
#line 14 "al.h"
typedef struct __anonstruct_profile_t_6 profile_t;
#line 24 "al.h"
struct __anonstruct_next_7 {
   struct _nest_t *sle_next ;
};
#line 24 "al.h"
struct _nest_t {
   profile_t *prof ;
   long level ;
   struct __anonstruct_next_7 next ;
};
#line 24 "al.h"
typedef struct _nest_t nest_t;
#line 30 "al.h"
struct __anonstruct_prof_list_9 {
   struct _nest_t *slh_first ;
};
#line 30 "al.h"
struct __anonstruct_thread_t_8 {
   Thread *stmThread ;
   struct __anonstruct_prof_list_9 prof_list ;
};
#line 30 "al.h"
typedef struct __anonstruct_thread_t_8 thread_t;
#line 22 "test2.c"
struct list_entry;
#line 22 "test2.c"
struct head {
   struct list_entry *lh_first ;
};
#line 24 "test2.c"
struct __anonstruct_links_10 {
   struct list_entry *le_next ;
   struct list_entry **le_prev ;
};
#line 24 "test2.c"
struct list_entry {
   long key ;
   long val ;
   struct __anonstruct_links_10 links ;
};
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned int  , void * ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned int  , char const   *  , ...) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned int  , int  , unsigned int  , char const   * 
                                , ...) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned int  , int  , unsigned int  , char const   * ,
                                 __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
#line 142 "/usr/include/stdio.h"
extern FILE __sF[] ;
#line 216
extern void clearerr(FILE * ) ;
#line 217
extern int fclose(FILE * ) ;
#line 218
extern int feof(FILE * ) ;
#line 219
extern int ferror(FILE * ) ;
#line 220
extern int fflush(FILE * ) ;
#line 221
extern int fgetc(FILE * ) ;
#line 222
extern int fgetpos(FILE * __restrict   , fpos_t * __restrict   ) ;
#line 223
extern char *fgets(char * __restrict   , int  , FILE * __restrict   ) ;
#line 224
extern FILE *fopen(char const   * , char const   * ) ;
#line 225
extern int fprintf(FILE * __restrict   , char const   * __restrict    , ...) ;
#line 226
extern int fputc(int  , FILE * ) ;
#line 227
extern int fputs(char const   * __restrict   , FILE * __restrict   ) ;
#line 228
extern size_t fread(void * __restrict   , size_t  , size_t  , FILE * __restrict   ) ;
#line 229
extern FILE *freopen(char const   * , char const   * , FILE * __restrict   ) ;
#line 230
extern int fscanf(FILE * __restrict   , char const   * __restrict    , ...) ;
#line 231
extern int fseek(FILE * , long  , int  ) ;
#line 232
extern int fsetpos(FILE * , fpos_t const   * ) ;
#line 233
extern long ftell(FILE * ) ;
#line 234
extern size_t fwrite(void const   * __restrict   , size_t  , size_t  , FILE * __restrict   ) ;
#line 236
extern int getc(FILE * ) ;
#line 237
extern int getchar(void) ;
#line 238
extern void perror(char const   * ) ;
#line 239
extern int printf(char const   * __restrict    , ...) ;
#line 240
extern int putc(int  , FILE * ) ;
#line 241
extern int putchar(int  ) ;
#line 242
extern int puts(char const   * ) ;
#line 243
extern int remove(char const   * ) ;
#line 244
extern void rewind(FILE * ) ;
#line 245
extern int scanf(char const   * __restrict    , ...) ;
#line 246
extern void setbuf(FILE * __restrict   , char * __restrict   ) ;
#line 247
extern int setvbuf(FILE * __restrict   , char * __restrict   , int  , size_t  ) ;
#line 248
extern int sscanf(char const   * __restrict   , char const   * __restrict    , ...) ;
#line 249
extern FILE *tmpfile(void) ;
#line 250
extern int ungetc(int  , FILE * ) ;
#line 251
extern int vfprintf(FILE * __restrict   , char const   * __restrict   , __builtin_va_list  ) ;
#line 253
extern int vfprintf_unlocked(FILE * __restrict   , char const   * __restrict   , __builtin_va_list  ) ;
#line 255
extern int vprintf(char const   * __restrict   , __builtin_va_list  ) ;
#line 258
extern char *gets(char * ) ;
#line 259
extern int sprintf(char * __restrict   , char const   * __restrict    , ...) ;
#line 260
extern char *tmpnam(char * ) ;
#line 261
extern int vsprintf(char * __restrict   , char const   * __restrict   , __builtin_va_list  ) ;
#line 268
extern int rename(char const   * , char const   * ) ;
#line 281
extern char *ctermid(char * ) ;
#line 285
extern char *cuserid(char * ) ;
#line 287
extern FILE *fdopen(int  , char const   * ) ;
#line 288
extern int fileno(FILE * ) ;
#line 298
extern void flockfile(FILE * ) ;
#line 299
extern int ftrylockfile(FILE * ) ;
#line 300
extern void funlockfile(FILE * ) ;
#line 301
extern int getc_unlocked(FILE * ) ;
#line 302
extern int getchar_unlocked(void) ;
#line 303
extern int putc_unlocked(int  , FILE * ) ;
#line 304
extern int putchar_unlocked(int  ) ;
#line 314
extern int pclose(FILE * ) ;
#line 315
extern FILE *popen(char const   * , char const   * ) ;
#line 324
extern int getw(FILE * ) ;
#line 325
extern int putw(int  , FILE * ) ;
#line 326
extern int ( /* format attribute */  snprintf)(char * __restrict   , size_t  , char const   * __restrict   
                                               , ...) ;
#line 328
extern int ( /* format attribute */  vsnprintf)(char * __restrict   , size_t  , char const   * __restrict   ,
                                                __builtin_va_list  ) ;
#line 333
extern char *tempnam(char const   * , char const   * ) ;
#line 349
extern int fseeko(FILE * , __off_t  , int  ) ;
#line 350
extern __off_t ftello(FILE * ) ;
#line 366
extern int ( /* format attribute */  asprintf)(char ** __restrict   , char const   * __restrict   
                                               , ...) ;
#line 368
extern char *fgetln(FILE * __restrict   , size_t * __restrict   ) ;
#line 369
extern char *fparseln(FILE * , size_t * , size_t * , char const   * , int  ) ;
#line 370
extern int fpurge(FILE * ) ;
#line 371
extern void setbuffer(FILE * , char * , int  ) ;
#line 372
extern int setlinebuf(FILE * ) ;
#line 373
extern int ( /* format attribute */  vasprintf)(char ** __restrict   , char const   * __restrict   ,
                                                __builtin_va_list  ) ;
#line 376
extern int ( /* format attribute */  vscanf)(char const   * __restrict   , __builtin_va_list  ) ;
#line 378
extern int ( /* format attribute */  vfscanf)(FILE * __restrict   , char const   * __restrict   ,
                                              __builtin_va_list  ) ;
#line 381
extern int ( /* format attribute */  vsscanf)(char const   * __restrict   , char const   * __restrict   ,
                                              __builtin_va_list  ) ;
#line 384
extern char const   *fmtcheck(char const   * , char const   * )  __attribute__((__format_arg__(2))) ;
#line 392
extern FILE *funopen(void const   * , int (*)(void * , char * , int  ) , int (*)(void * ,
                                                                                 char const   * ,
                                                                                 int  ) ,
                     fpos_t (*)(void * , fpos_t  , int  ) , int (*)(void * ) ) ;
#line 406
extern int __srget(FILE * ) ;
#line 407
extern int __swbuf(int  , FILE * ) ;
#line 416 "/usr/include/stdio.h"
__inline static int __sputc(int _c , FILE *_p ) 
{ unsigned char *tmp ;
  int tmp___0 ;

  {
#line 417
  (_p->_w) --;
#line 417
  if (_p->_w >= 0) {
#line 418
    tmp = _p->_p;
#line 418
    (_p->_p) ++;
#line 418
    *tmp = (unsigned char )_c;
#line 418
    return ((int )*tmp);
  } else {
#line 417
    if (_p->_w >= _p->_lbfsize) {
#line 417
      if ((int )((char )_c) != 10) {
#line 418
        tmp = _p->_p;
#line 418
        (_p->_p) ++;
#line 418
        *tmp = (unsigned char )_c;
#line 418
        return ((int )*tmp);
      } else {
#line 420
        tmp___0 = __swbuf(_c, _p);
#line 420
        return (tmp___0);
      }
    } else {
#line 420
      tmp___0 = __swbuf(_c, _p);
#line 420
      return (tmp___0);
    }
  }
}
}
#line 49 "/usr/include/machine/byte_swap.h"
__inline static u_int32_t __byte_swap_long_variable(u_int32_t x ) ;
#line 50
__inline static u_int16_t __byte_swap_word_variable(u_int16_t x ) ;
#line 52 "/usr/include/machine/byte_swap.h"
__inline static u_int32_t __byte_swap_long_variable(u_int32_t x ) 
{ 

  {
#line 55
  __asm__  volatile   ("rorw $8, %w1\n\trorl $16, %1\n\trorw $8, %w1": "=r" (x): "0" (x));
#line 62
  return (x);
}
}
#line 65 "/usr/include/machine/byte_swap.h"
__inline static u_int16_t __byte_swap_word_variable(u_int16_t x ) 
{ 

  {
#line 68
  __asm__  volatile   ("rorw $8, %w1": "=r" (x): "0" (x));
#line 69
  return (x);
}
}
#line 92 "/usr/include/sys/endian.h"
extern __uint32_t htonl(__uint32_t  )  __attribute__((__const__)) ;
#line 93
extern __uint16_t htons(__uint16_t  )  __attribute__((__const__)) ;
#line 94
extern __uint32_t ntohl(__uint32_t  )  __attribute__((__const__)) ;
#line 95
extern __uint16_t ntohs(__uint16_t  )  __attribute__((__const__)) ;
#line 21 "/usr/include/sys/bswap.h"
extern u_int16_t bswap16(u_int16_t  )  __asm__("__bswap16")  ;
#line 22
extern u_int32_t bswap32(u_int32_t  )  __asm__("__bswap32")  ;
#line 24
extern u_int64_t bswap64(u_int64_t  ) ;
#line 223 "/usr/include/sys/types.h"
extern __off_t lseek(int  , __off_t  , int  ) ;
#line 224
extern int ftruncate(int  , __off_t  ) ;
#line 225
extern int truncate(char const   * , __off_t  ) ;
#line 92 "/usr/include/stdlib.h"
extern size_t __mb_cur_max ;
#line 96
extern  __attribute__((__noreturn__)) void _Exit(int  ) ;
#line 97
extern  __attribute__((__noreturn__)) void abort(void) ;
#line 98
extern int abs(int  ) ;
#line 99
extern int atexit(void (*)(void) ) ;
#line 100
extern double atof(char const   * ) ;
#line 101
extern int atoi(char const   * ) ;
#line 102
extern long atol(char const   * ) ;
#line 106
extern void *bsearch(void const   * , void const   * , size_t  , size_t  , int (*)(void const   * ,
                                                                                   void const   * ) ) ;
#line 109
extern void *calloc(size_t  , size_t  ) ;
#line 110
extern div_t div(int  , int  ) ;
#line 111
extern  __attribute__((__noreturn__)) void exit(int  ) ;
#line 112
extern void free(void * ) ;
#line 113
extern char *getenv(char const   * ) ;
#line 114
extern long labs(long  ) ;
#line 116
extern ldiv_t ldiv(long  , long  ) ;
#line 117
extern void *malloc(size_t  ) ;
#line 118
extern void qsort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 120
extern int rand(void) ;
#line 121
extern void *realloc(void * , size_t  ) ;
#line 122
extern void srand(unsigned int  ) ;
#line 123
extern double strtod(char const   * __restrict   , char ** __restrict   ) ;
#line 124
extern long strtol(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 125
extern unsigned long strtoul(char const   * __restrict   , char ** __restrict   ,
                             int  ) ;
#line 127
extern int system(char const   * ) ;
#line 130
extern int mblen(char const   * , size_t  ) ;
#line 131
extern size_t mbstowcs(wchar_t * __restrict   , char const   * __restrict   , size_t  ) ;
#line 132
extern int wctomb(char * , wchar_t  ) ;
#line 133
extern int mbtowc(wchar_t * __restrict   , char const   * __restrict   , size_t  ) ;
#line 134
extern size_t wcstombs(char * __restrict   , wchar_t const   * __restrict   , size_t  ) ;
#line 145
extern int rand_r(unsigned int * ) ;
#line 153
extern double drand48(void) ;
#line 154
extern double erand48(unsigned short * ) ;
#line 155
extern long jrand48(unsigned short * ) ;
#line 156
extern void lcong48(unsigned short * ) ;
#line 157
extern long lrand48(void) ;
#line 158
extern long mrand48(void) ;
#line 159
extern long nrand48(unsigned short * ) ;
#line 160
extern unsigned short *seed48(unsigned short * ) ;
#line 162
extern void srand48(long  ) ;
#line 164
extern int putenv(char const   * ) ;
#line 173
extern long a64l(char const   * ) ;
#line 174
extern char *l64a(long  ) ;
#line 176
extern char *initstate(unsigned long  , char * , size_t  ) ;
#line 177
extern long random(void) ;
#line 178
extern char *setstate(char * ) ;
#line 179
extern void srandom(unsigned long  ) ;
#line 181
extern char *mkdtemp(char * ) ;
#line 182
extern int mkstemp(char * ) ;
#line 184
extern char *mktemp(char * ) ;
#line 187
extern int setkey(char const   * ) ;
#line 189
extern char *realpath(char const   * , char * ) ;
#line 191
extern int ttyslot(void) ;
#line 193
extern void *valloc(size_t  ) ;
#line 202
extern long long atoll(char const   * ) ;
#line 204
extern long long llabs(long long  ) ;
#line 206
extern lldiv_t lldiv(long long  , long long  ) ;
#line 208
extern long long strtoll(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 210
extern unsigned long long strtoull(char const   * __restrict   , char ** __restrict   ,
                                   int  ) ;
#line 220
extern int setenv(char const   * , char const   * , int  ) ;
#line 225
extern int unsetenv(char const   * )  __asm__("__unsetenv13")  ;
#line 236
extern void *alloca(size_t  ) ;
#line 239
extern u_int32_t arc4random(void) ;
#line 240
extern void arc4random_stir(void) ;
#line 241
extern void arc4random_addrandom(u_char * , int  ) ;
#line 242
extern char *getbsize(int * , long * ) ;
#line 243
extern char *cgetcap(char * , char const   * , int  ) ;
#line 244
extern int cgetclose(void) ;
#line 245
extern int cgetent(char ** , char ** , char const   * ) ;
#line 246
extern int cgetfirst(char ** , char ** ) ;
#line 247
extern int cgetmatch(char const   * , char const   * ) ;
#line 248
extern int cgetnext(char ** , char ** ) ;
#line 249
extern int cgetnum(char * , char const   * , long * ) ;
#line 250
extern int cgetset(char const   * ) ;
#line 251
extern int cgetstr(char * , char const   * , char ** ) ;
#line 252
extern int cgetustr(char * , char const   * , char ** ) ;
#line 254
extern int daemon(int  , int  ) ;
#line 255
extern char *devname(dev_t  , __mode_t  ) ;
#line 256
extern int getloadavg(double * , int  ) ;
#line 258
extern void cfree(void * ) ;
#line 260
extern int heapsort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 262
extern int mergesort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 264
extern int radixsort(unsigned char const   ** , int  , unsigned char const   * , unsigned int  ) ;
#line 266
extern int sradixsort(unsigned char const   ** , int  , unsigned char const   * ,
                      unsigned int  ) ;
#line 269
extern void ( /* format attribute */  setproctitle)(char const   *  , ...) ;
#line 271
extern char const   *getprogname(void)  __attribute__((__const__)) ;
#line 272
extern void setprogname(char const   * ) ;
#line 274
extern quad_t qabs(quad_t  ) ;
#line 275
extern quad_t strtoq(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 276
extern u_quad_t strtouq(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 279
extern long long strsuftoll(char const   * , char const   * , long long  , long long  ) ;
#line 281
extern long long strsuftollx(char const   * , char const   * , long long  , long long  ,
                             char * , size_t  ) ;
#line 284
extern int l64a_r(long  , char * , int  ) ;
#line 286
extern size_t shquote(char const   * , char * , size_t  ) ;
#line 287
extern size_t shquotev(int  , char * const  * , char * , size_t  ) ;
#line 292
extern qdiv_t qdiv(quad_t  , quad_t  ) ;
#line 49 "/usr/include/string.h"
extern void *memchr(void const   * , int  , size_t  ) ;
#line 50
extern int memcmp(void const   * , void const   * , size_t  ) ;
#line 51
extern void *memcpy(void * __restrict   , void const   * __restrict   , size_t  ) ;
#line 52
extern void *memmove(void * , void const   * , size_t  ) ;
#line 53
extern void *memset(void * , int  , size_t  ) ;
#line 54
extern char *strcat(char * __restrict   , char const   * __restrict   ) ;
#line 55
extern char *strchr(char const   * , int  ) ;
#line 56
extern int strcmp(char const   * , char const   * ) ;
#line 57
extern int strcoll(char const   * , char const   * ) ;
#line 58
extern char *strcpy(char * __restrict   , char const   * __restrict   ) ;
#line 59
extern size_t strcspn(char const   * , char const   * ) ;
#line 60
extern char *strerror(int  ) ;
#line 61
extern size_t strlen(char const   * ) ;
#line 62
extern char *strncat(char * __restrict   , char const   * __restrict   , size_t  ) ;
#line 63
extern int strncmp(char const   * , char const   * , size_t  ) ;
#line 64
extern char *strncpy(char * __restrict   , char const   * __restrict   , size_t  ) ;
#line 65
extern char *strpbrk(char const   * , char const   * ) ;
#line 66
extern char *strrchr(char const   * , int  ) ;
#line 67
extern size_t strspn(char const   * , char const   * ) ;
#line 68
extern char *strstr(char const   * , char const   * ) ;
#line 69
extern char *strtok(char * __restrict   , char const   * __restrict   ) ;
#line 72
extern char *strtok_r(char * , char const   * , char ** ) ;
#line 74
extern size_t strxfrm(char * __restrict   , char const   * __restrict   , size_t  ) ;
#line 77
extern void *memccpy(void * , void const   * , int  , size_t  ) ;
#line 78
extern char *strdup(char const   * ) ;
#line 57 "/usr/include/strings.h"
extern int bcmp(void const   * , void const   * , size_t  ) ;
#line 58
extern void bcopy(void const   * , void * , size_t  ) ;
#line 59
extern void bzero(void * , size_t  ) ;
#line 60
extern int ffs(int  ) ;
#line 61
extern char *index(char const   * , int  ) ;
#line 62
extern char *rindex(char const   * , int  ) ;
#line 63
extern int strcasecmp(char const   * , char const   * ) ;
#line 64
extern int strncasecmp(char const   * , char const   * , size_t  ) ;
#line 83 "/usr/include/string.h"
extern char *strcasestr(char const   * , char const   * ) ;
#line 84
extern size_t strlcat(char * , char const   * , size_t  ) ;
#line 85
extern size_t strlcpy(char * , char const   * , size_t  ) ;
#line 86
extern char *strsep(char ** , char const   * ) ;
#line 91 "/usr/include/unistd.h"
extern  __attribute__((__noreturn__)) void _exit(int  ) ;
#line 92
extern int access(char const   * , int  ) ;
#line 93
extern unsigned int alarm(unsigned int  ) ;
#line 94
extern int chdir(char const   * ) ;
#line 98
extern int chown(char const   * , __uid_t  , __gid_t  ) ;
#line 100
extern int close(int  ) ;
#line 101
extern size_t confstr(int  , char * , size_t  ) ;
#line 107
extern int dup(int  ) ;
#line 108
extern int dup2(int  , int  ) ;
#line 109
extern int execl(char const   * , char const   *  , ...) ;
#line 110
extern int execle(char const   * , char const   *  , ...) ;
#line 111
extern int execlp(char const   * , char const   *  , ...) ;
#line 112
extern int execv(char const   * , char * const  * ) ;
#line 113
extern int execve(char const   * , char * const  * , char * const  * ) ;
#line 114
extern int execvp(char const   * , char * const  * ) ;
#line 115
extern __pid_t fork(void) ;
#line 116
extern long fpathconf(int  , int  ) ;
#line 117
extern char *getcwd(char * , size_t  ) ;
#line 118
extern __gid_t getegid(void) ;
#line 119
extern __uid_t geteuid(void) ;
#line 120
extern __gid_t getgid(void) ;
#line 121
extern int getgroups(int  , __gid_t * ) ;
#line 122
extern char *getlogin(void) ;
#line 123
extern __pid_t getpgrp(void) ;
#line 124
extern __pid_t getpid(void) ;
#line 125
extern __pid_t getppid(void) ;
#line 126
extern __uid_t getuid(void) ;
#line 127
extern int isatty(int  ) ;
#line 128
extern int link(char const   * , char const   * ) ;
#line 129
extern long pathconf(char const   * , int  ) ;
#line 130
extern int pause(void) ;
#line 131
extern int pipe(int * ) ;
#line 132
extern ssize_t read(int  , void * , size_t  ) ;
#line 133
extern int rmdir(char const   * ) ;
#line 134
extern int setgid(__gid_t  ) ;
#line 135
extern int setpgid(__pid_t  , __pid_t  ) ;
#line 136
extern __pid_t setsid(void) ;
#line 137
extern int setuid(__uid_t  ) ;
#line 138
extern unsigned int sleep(unsigned int  ) ;
#line 139
extern long sysconf(int  ) ;
#line 140
extern __pid_t tcgetpgrp(int  ) ;
#line 141
extern int tcsetpgrp(int  , __pid_t  ) ;
#line 142
extern char *ttyname(int  ) ;
#line 143
extern int unlink(char const   * ) ;
#line 144
extern ssize_t write(int  , void const   * , size_t  ) ;
#line 152
extern int getopt(int  , char * const  * , char const   * ) ;
#line 154
extern char *optarg ;
#line 155
extern int opterr ;
#line 156
extern int optind ;
#line 157
extern int optopt ;
#line 165
extern int setegid(__gid_t  ) ;
#line 166
extern int seteuid(__uid_t  ) ;
#line 194
extern int fdatasync(int  ) ;
#line 195
extern int fsync(int  ) ;
#line 203
extern int chroot(char const   * ) ;
#line 204
extern int nice(int  ) ;
#line 220
extern char *crypt(char const   * , char const   * ) ;
#line 221
extern int encrypt(char * , int  ) ;
#line 222
extern char *getpass(char const   * ) ;
#line 223
extern __pid_t getsid(__pid_t  ) ;
#line 242
extern int brk(void * ) ;
#line 243
extern int fchdir(int  ) ;
#line 247
extern int fchown(int  , __uid_t  , __gid_t  ) ;
#line 249
extern int getdtablesize(void) ;
#line 250
extern long gethostid(void) ;
#line 251
extern int gethostname(char * , size_t  ) ;
#line 252
extern int getpagesize(void) ;
#line 254
extern __pid_t getpgid(__pid_t  ) ;
#line 258
extern int lchown(char const   * , __uid_t  , __gid_t  ) ;
#line 260
extern int lockf(int  , int  , __off_t  ) ;
#line 261
extern int readlink(char const   * , char * , size_t  ) ;
#line 262
extern void *sbrk(__intptr_t  ) ;
#line 264
extern int setpgrp(__pid_t  , __pid_t  ) ;
#line 265
extern int setregid(__gid_t  , __gid_t  ) ;
#line 266
extern int setreuid(__uid_t  , __uid_t  ) ;
#line 267
extern void swab(void const   * , void * , size_t  ) ;
#line 268
extern int symlink(char const   * , char const   * ) ;
#line 269
extern void sync(void) ;
#line 270
extern useconds_t ualarm(useconds_t  , useconds_t  ) ;
#line 271
extern int usleep(useconds_t  ) ;
#line 276
extern __pid_t vfork(void)  __asm__("__vfork14")  ;
#line 280
extern char *getwd(char * ) ;
#line 287
extern int select(int  , fd_set * , fd_set * , fd_set * , struct timeval * ) ;
#line 295
extern ssize_t pread(int  , void * , size_t  , __off_t  ) ;
#line 296
extern ssize_t pwrite(int  , void const   * , size_t  , __off_t  ) ;
#line 304
extern int acct(char const   * ) ;
#line 305
extern int des_cipher(char const   * , char * , long  , int  ) ;
#line 306
extern int des_setkey(char const   * ) ;
#line 307
extern void endusershell(void) ;
#line 308
extern int exect(char const   * , char * const  * , char * const  * ) ;
#line 309
extern int fchroot(int  ) ;
#line 310
extern int fsync_range(int  , int  , __off_t  , __off_t  ) ;
#line 311
extern int getdomainname(char * , size_t  ) ;
#line 312
extern int getgrouplist(char const   * , __gid_t  , __gid_t * , int * ) ;
#line 313
extern __mode_t getmode(void const   * , __mode_t  ) ;
#line 314
extern int getsubopt(char ** , char * const  * , char ** ) ;
#line 315
extern char *getusershell(void) ;
#line 316
extern int initgroups(char const   * , __gid_t  ) ;
#line 317
extern int iruserok(u_int32_t  , int  , char const   * , char const   * ) ;
#line 318
extern int issetugid(void) ;
#line 319
extern int nfssvc(int  , void * ) ;
#line 320
extern int profil(char * , size_t  , u_long  , u_int  ) ;
#line 324
extern void psignal(unsigned int  , char const   * ) ;
#line 326
extern int rcmd(char ** , int  , char const   * , char const   * , char const   * ,
                int * ) ;
#line 328
extern int reboot(int  , char * ) ;
#line 329
extern int revoke(char const   * ) ;
#line 330
extern int rresvport(int * ) ;
#line 331
extern int ruserok(char const   * , int  , char const   * , char const   * ) ;
#line 332
extern int setdomainname(char const   * , size_t  ) ;
#line 333
extern int setgroups(int  , __gid_t const   * ) ;
#line 334
extern int sethostid(long  ) ;
#line 335
extern int sethostname(char const   * , size_t  ) ;
#line 336
extern int setlogin(char const   * ) ;
#line 337
extern void *setmode(char const   * ) ;
#line 338
extern int setrgid(__gid_t  ) ;
#line 339
extern int setruid(__uid_t  ) ;
#line 340
extern void setusershell(void) ;
#line 341
extern void strmode(__mode_t  , char * ) ;
#line 342
extern char *strsignal(int  ) ;
#line 343
extern int swapctl(int  , void const   * , int  ) ;
#line 344
extern int swapon(char const   * ) ;
#line 345
extern int syscall(int   , ...) ;
#line 346
extern quad_t __syscall(quad_t   , ...) ;
#line 347
extern int undelete(char const   * ) ;
#line 350
extern int rcmd_af(char ** , int  , char const   * , char const   * , char const   * ,
                   int * , int  ) ;
#line 352
extern int rresvport_af(int * , int  ) ;
#line 353
extern int iruserok_sa(void const   * , int  , int  , char const   * , char const   * ) ;
#line 359
extern char const   * const  *sys_siglist  __asm__("__sys_siglist14")  ;
#line 361
extern int optreset ;
#line 362
extern char *suboptarg ;
#line 98 "/usr/include/assert.h"
extern void __assert(char const   * , int  , char const   * ) ;
#line 99
extern void __assert13(char const   * , int  , char const   * , char const   * ) ;
#line 100
extern void __diagassert(char const   * , int  , char const   * ) ;
#line 101
extern void __diagassert13(char const   * , int  , char const   * , char const   * ) ;
#line 90 "/usr/include/time.h"
extern char *asctime(struct tm  const  * ) ;
#line 91
extern clock_t clock(void) ;
#line 92
extern char *ctime(time_t const   * ) ;
#line 93
extern double difftime(time_t  , time_t  ) ;
#line 94
extern struct tm *gmtime(time_t const   * ) ;
#line 95
extern struct tm *localtime(time_t const   * ) ;
#line 96
extern time_t mktime(struct tm * ) ;
#line 97
extern size_t strftime(char * __restrict   , size_t  , char const   * __restrict   ,
                       struct tm  const  * __restrict   ) ;
#line 99
extern time_t time(time_t * ) ;
#line 113
extern long __sysconf(int  ) ;
#line 118
extern char *tzname[2] ;
#line 119
extern void tzset(void) ;
#line 125
extern int daylight ;
#line 127
extern long timezone  __asm__("__timezone13")  ;
#line 129
extern char *strptime(char const   * __restrict   , char const   * __restrict   ,
                      struct tm * __restrict   ) ;
#line 237 "/usr/include/sys/time.h"
extern int adjtime(struct timeval  const  * , struct timeval * ) ;
#line 238
extern int futimes(int  , struct timeval  const  * ) ;
#line 239
extern int getitimer(int  , struct itimerval * ) ;
#line 240
extern int gettimeofday(struct timeval * , struct timezone * ) ;
#line 241
extern int lutimes(char const   * , struct timeval  const  * ) ;
#line 242
extern int setitimer(int  , struct itimerval  const  * , struct itimerval * ) ;
#line 243
extern int settimeofday(struct timeval  const  * , struct timezone  const  * ) ;
#line 244
extern int utimes(char const   * , struct timeval  const  * ) ;
#line 138 "/usr/include/time.h"
extern int clock_getres(clockid_t  , struct timespec * ) ;
#line 139
extern int clock_gettime(clockid_t  , struct timespec * ) ;
#line 140
extern int clock_settime(clockid_t  , struct timespec  const  * ) ;
#line 141
extern int nanosleep(struct timespec  const  * , struct timespec * ) ;
#line 142
extern int timer_create(clockid_t  , struct sigevent * __restrict   , timer_t * __restrict   ) ;
#line 144
extern int timer_delete(timer_t  ) ;
#line 145
extern int timer_getoverrun(timer_t  ) ;
#line 146
extern int timer_gettime(timer_t  , struct itimerspec * ) ;
#line 147
extern int timer_settime(timer_t  , int  , struct itimerspec  const  * __restrict   ,
                         struct itimerspec * __restrict   ) ;
#line 153
extern char *asctime_r(struct tm  const  * __restrict   , char * __restrict   ) ;
#line 154
extern char *ctime_r(time_t const   * , char * ) ;
#line 155
extern struct tm *gmtime_r(time_t const   * __restrict   , struct tm * __restrict   ) ;
#line 156
extern struct tm *localtime_r(time_t const   * __restrict   , struct tm * __restrict   ) ;
#line 160
extern time_t time2posix(time_t  ) ;
#line 161
extern time_t posix2time(time_t  ) ;
#line 162
extern time_t timegm(struct tm * ) ;
#line 163
extern time_t timeoff(struct tm * , long  ) ;
#line 164
extern time_t timelocal(struct tm * ) ;
#line 168
extern void tzsetwall(void) ;
#line 169
extern struct tm *offtime(time_t const   * , long  ) ;
#line 56 "/usr/include/sched.h"
extern int sched_setparam(__pid_t  , struct sched_param  const  * ) ;
#line 57
extern int sched_getparam(__pid_t  , struct sched_param * ) ;
#line 58
extern int sched_setscheduler(__pid_t  , int  , struct sched_param  const  * ) ;
#line 59
extern int sched_getscheduler(__pid_t  ) ;
#line 60
extern int sched_get_priority_max(int  ) ;
#line 61
extern int sched_get_priority_min(int  ) ;
#line 62
extern int sched_rr_get_interval(__pid_t  , struct timespec * ) ;
#line 66
extern int sched_yield(void) ;
#line 77
extern __pid_t clone(int (*)(void * ) , void * , int  , void * ) ;
#line 78
extern __pid_t __clone(int (*)(void * ) , void * , int  , void * ) ;
#line 50 "/usr/include/pthread.h"
extern int pthread_atfork(void (*)(void) , void (*)(void) , void (*)(void) ) ;
#line 51
extern int pthread_create(pthread_t * , pthread_attr_t const   * , void *(*)(void * ) ,
                          void * ) ;
#line 53
extern  __attribute__((__noreturn__)) void pthread_exit(void * ) ;
#line 54
extern int pthread_join(pthread_t  , void ** ) ;
#line 55
extern int pthread_equal(pthread_t  , pthread_t  ) ;
#line 56
extern pthread_t pthread_self(void) ;
#line 57
extern int pthread_detach(pthread_t  ) ;
#line 59
extern int pthread_getrrtimer_np(void) ;
#line 60
extern int pthread_setrrtimer_np(int  ) ;
#line 62
extern int pthread_attr_init(pthread_attr_t * ) ;
#line 63
extern int pthread_attr_destroy(pthread_attr_t * ) ;
#line 64
extern int pthread_attr_get_np(pthread_t  , pthread_attr_t * ) ;
#line 65
extern int pthread_attr_getguardsize(pthread_attr_t const   * , size_t * ) ;
#line 66
extern int pthread_attr_setguardsize(pthread_attr_t * , size_t  ) ;
#line 67
extern int pthread_attr_getinheritsched(pthread_attr_t const   * , int * ) ;
#line 68
extern int pthread_attr_setinheritsched(pthread_attr_t * , int  ) ;
#line 69
extern int pthread_attr_getschedparam(pthread_attr_t const   * , struct sched_param * ) ;
#line 71
extern int pthread_attr_setschedparam(pthread_attr_t * , struct sched_param  const  * ) ;
#line 73
extern int pthread_attr_getscope(pthread_attr_t const   * , int * ) ;
#line 74
extern int pthread_attr_setscope(pthread_attr_t * , int  ) ;
#line 75
extern int pthread_attr_getstack(pthread_attr_t const   * , void ** , size_t * ) ;
#line 76
extern int pthread_attr_setstack(pthread_attr_t * , void * , size_t  ) ;
#line 77
extern int pthread_attr_getstacksize(pthread_attr_t const   * , size_t * ) ;
#line 78
extern int pthread_attr_setstacksize(pthread_attr_t * , size_t  ) ;
#line 79
extern int pthread_attr_getstackaddr(pthread_attr_t const   * , void ** ) ;
#line 80
extern int pthread_attr_setstackaddr(pthread_attr_t * , void * ) ;
#line 81
extern int pthread_attr_getdetachstate(pthread_attr_t const   * , int * ) ;
#line 82
extern int pthread_attr_setdetachstate(pthread_attr_t * , int  ) ;
#line 83
extern int pthread_attr_getname_np(pthread_attr_t const   * , char * , size_t  , void ** ) ;
#line 85
extern int pthread_attr_setname_np(pthread_attr_t * , char const   * , void * ) ;
#line 87
extern int pthread_mutex_init(pthread_mutex_t * , pthread_mutexattr_t const   * ) ;
#line 88
extern int pthread_mutex_destroy(pthread_mutex_t * ) ;
#line 89
extern int pthread_mutex_lock(pthread_mutex_t * ) ;
#line 90
extern int pthread_mutex_trylock(pthread_mutex_t * ) ;
#line 91
extern int pthread_mutex_unlock(pthread_mutex_t * ) ;
#line 92
extern int pthread_mutexattr_init(pthread_mutexattr_t * ) ;
#line 93
extern int pthread_mutexattr_destroy(pthread_mutexattr_t * ) ;
#line 94
extern int pthread_mutexattr_gettype(pthread_mutexattr_t const   * , int * ) ;
#line 95
extern int pthread_mutexattr_settype(pthread_mutexattr_t *attr , int  ) ;
#line 97
extern int pthread_cond_init(pthread_cond_t * , pthread_condattr_t const   * ) ;
#line 98
extern int pthread_cond_destroy(pthread_cond_t * ) ;
#line 99
extern int pthread_cond_wait(pthread_cond_t * , pthread_mutex_t * ) ;
#line 100
extern int pthread_cond_timedwait(pthread_cond_t * , pthread_mutex_t * , struct timespec  const  * ) ;
#line 102
extern int pthread_cond_signal(pthread_cond_t * ) ;
#line 103
extern int pthread_cond_broadcast(pthread_cond_t * ) ;
#line 104
extern int pthread_condattr_init(pthread_condattr_t * ) ;
#line 105
extern int pthread_condattr_destroy(pthread_condattr_t * ) ;
#line 107
extern int pthread_once(pthread_once_t * , void (*)(void) ) ;
#line 109
extern int pthread_key_create(pthread_key_t * , void (*)(void * ) ) ;
#line 110
extern int pthread_key_delete(pthread_key_t  ) ;
#line 111
extern int pthread_setspecific(pthread_key_t  , void const   * ) ;
#line 112
extern void *pthread_getspecific(pthread_key_t  ) ;
#line 114
extern int pthread_cancel(pthread_t  ) ;
#line 115
extern int pthread_setcancelstate(int  , int * ) ;
#line 116
extern int pthread_setcanceltype(int  , int * ) ;
#line 117
extern void pthread_testcancel(void) ;
#line 119
extern int pthread_getname_np(pthread_t  , char * , size_t  ) ;
#line 120
extern int pthread_setname_np(pthread_t  , char const   * , void * ) ;
#line 122
extern int pthread_attr_setcreatesuspend_np(pthread_attr_t * ) ;
#line 123
extern int pthread_suspend_np(pthread_t  ) ;
#line 124
extern int pthread_resume_np(pthread_t  ) ;
#line 139
extern void pthread__cleanup_push(void (*)(void * ) , void * , void * ) ;
#line 140
extern void pthread__cleanup_pop(int  , void * ) ;
#line 142
extern int pthread_spin_init(pthread_spinlock_t * , int  ) ;
#line 143
extern int pthread_spin_destroy(pthread_spinlock_t * ) ;
#line 144
extern int pthread_spin_lock(pthread_spinlock_t * ) ;
#line 145
extern int pthread_spin_trylock(pthread_spinlock_t * ) ;
#line 146
extern int pthread_spin_unlock(pthread_spinlock_t * ) ;
#line 148
extern int pthread_rwlock_init(pthread_rwlock_t * , pthread_rwlockattr_t const   * ) ;
#line 150
extern int pthread_rwlock_destroy(pthread_rwlock_t * ) ;
#line 151
extern int pthread_rwlock_rdlock(pthread_rwlock_t * ) ;
#line 152
extern int pthread_rwlock_tryrdlock(pthread_rwlock_t * ) ;
#line 153
extern int pthread_rwlock_wrlock(pthread_rwlock_t * ) ;
#line 154
extern int pthread_rwlock_trywrlock(pthread_rwlock_t * ) ;
#line 155
extern int pthread_rwlock_timedrdlock(pthread_rwlock_t * , struct timespec  const  * ) ;
#line 157
extern int pthread_rwlock_timedwrlock(pthread_rwlock_t * , struct timespec  const  * ) ;
#line 159
extern int pthread_rwlock_unlock(pthread_rwlock_t * ) ;
#line 160
extern int pthread_rwlockattr_init(pthread_rwlockattr_t * ) ;
#line 161
extern int pthread_rwlockattr_destroy(pthread_rwlockattr_t * ) ;
#line 163
extern int pthread_barrier_init(pthread_barrier_t * , pthread_barrierattr_t const   * ,
                                unsigned int  ) ;
#line 165
extern int pthread_barrier_wait(pthread_barrier_t * ) ;
#line 166
extern int pthread_barrier_destroy(pthread_barrier_t * ) ;
#line 167
extern int pthread_barrierattr_init(pthread_barrierattr_t * ) ;
#line 168
extern int pthread_barrierattr_destroy(pthread_barrierattr_t * ) ;
#line 170
extern int pthread_getschedparam(pthread_t  , int * , struct sched_param * ) ;
#line 171
extern int pthread_setschedparam(pthread_t  , int  , struct sched_param  const  * ) ;
#line 173
extern int *pthread__errno(void) ;
#line 68 "/usr/include/setjmp.h"
extern int setjmp(long * )  __asm__("__setjmp14")  ;
#line 69
extern void longjmp(long * , int  )  __asm__("__longjmp14")  ;
#line 73
extern int sigsetjmp(long * , int  )  __asm__("__sigsetjmp14")  ;
#line 74
extern void siglongjmp(long * , int  )  __asm__("__siglongjmp14")  ;
#line 79
extern int _setjmp(long * ) ;
#line 80
extern void _longjmp(long * , int  ) ;
#line 84
extern void longjmperror(void) ;
#line 105 "/usr/include/wchar.h"
extern wint_t btowc(int  ) ;
#line 106
extern size_t mbrlen(char const   * __restrict   , size_t  , mbstate_t * __restrict   ) ;
#line 107
extern size_t mbrtowc(wchar_t * __restrict   , char const   * __restrict   , size_t  ,
                      mbstate_t * __restrict   ) ;
#line 109
extern int mbsinit(mbstate_t const   * ) ;
#line 110
extern size_t mbsrtowcs(wchar_t * __restrict   , char const   ** __restrict   , size_t  ,
                        mbstate_t * __restrict   ) ;
#line 112
extern size_t wcrtomb(char * __restrict   , wchar_t  , mbstate_t * __restrict   ) ;
#line 113
extern wchar_t *wcscat(wchar_t * __restrict   , wchar_t const   * __restrict   ) ;
#line 114
extern wchar_t *wcschr(wchar_t const   * , wchar_t  ) ;
#line 115
extern int wcscmp(wchar_t const   * , wchar_t const   * ) ;
#line 116
extern int wcscoll(wchar_t const   * , wchar_t const   * ) ;
#line 117
extern wchar_t *wcscpy(wchar_t * __restrict   , wchar_t const   * __restrict   ) ;
#line 118
extern size_t wcscspn(wchar_t const   * , wchar_t const   * ) ;
#line 119
extern size_t wcslen(wchar_t const   * ) ;
#line 120
extern wchar_t *wcsncat(wchar_t * __restrict   , wchar_t const   * __restrict   ,
                        size_t  ) ;
#line 122
extern int wcsncmp(wchar_t const   * , wchar_t const   * , size_t  ) ;
#line 123
extern wchar_t *wcsncpy(wchar_t * __restrict   , wchar_t const   * __restrict   ,
                        size_t  ) ;
#line 125
extern wchar_t *wcspbrk(wchar_t const   * , wchar_t const   * ) ;
#line 126
extern wchar_t *wcsrchr(wchar_t const   * , wchar_t  ) ;
#line 127
extern size_t wcsrtombs(char * __restrict   , wchar_t const   ** __restrict   , size_t  ,
                        mbstate_t * __restrict   ) ;
#line 129
extern size_t wcsspn(wchar_t const   * , wchar_t const   * ) ;
#line 130
extern wchar_t *wcsstr(wchar_t const   * , wchar_t const   * ) ;
#line 131
extern wchar_t *wcstok(wchar_t * __restrict   , wchar_t const   * __restrict   , wchar_t ** __restrict   ) ;
#line 133
extern size_t wcsxfrm(wchar_t * , wchar_t const   * , size_t  ) ;
#line 134
extern wchar_t *wcswcs(wchar_t const   * , wchar_t const   * ) ;
#line 135
extern wchar_t *wmemchr(wchar_t const   * , wchar_t  , size_t  ) ;
#line 136
extern int wmemcmp(wchar_t const   * , wchar_t const   * , size_t  ) ;
#line 137
extern wchar_t *wmemcpy(wchar_t * __restrict   , wchar_t const   * __restrict   ,
                        size_t  ) ;
#line 139
extern wchar_t *wmemmove(wchar_t * , wchar_t const   * , size_t  ) ;
#line 140
extern wchar_t *wmemset(wchar_t * , wchar_t  , size_t  ) ;
#line 142
extern size_t wcslcat(wchar_t * , wchar_t const   * , size_t  ) ;
#line 143
extern size_t wcslcpy(wchar_t * , wchar_t const   * , size_t  ) ;
#line 144
extern int wcswidth(wchar_t const   * , size_t  ) ;
#line 145
extern int wctob(wint_t  ) ;
#line 146
extern int wcwidth(wchar_t  ) ;
#line 148
extern unsigned long wcstoul(wchar_t const   * __restrict   , wchar_t ** __restrict   ,
                             int  ) ;
#line 150
extern long wcstol(wchar_t const   * __restrict   , wchar_t ** __restrict   , int  ) ;
#line 152
extern double wcstod(wchar_t const   * __restrict   , wchar_t ** __restrict   ) ;
#line 157
extern long long wcstoll(wchar_t const   * __restrict   , wchar_t ** __restrict   ,
                         int  ) ;
#line 160
extern unsigned long long wcstoull(wchar_t const   * __restrict   , wchar_t ** __restrict   ,
                                   int  ) ;
#line 164
extern wint_t ungetwc(wint_t  , FILE * ) ;
#line 165
extern wint_t fgetwc(FILE * ) ;
#line 166
extern wchar_t *fgetws(wchar_t * __restrict   , int  , FILE * __restrict   ) ;
#line 167
extern wint_t getwc(FILE * ) ;
#line 168
extern wint_t getwchar(void) ;
#line 169
extern wint_t fputwc(wchar_t  , FILE * ) ;
#line 170
extern int fputws(wchar_t const   * __restrict   , FILE * __restrict   ) ;
#line 171
extern wint_t putwc(wchar_t  , FILE * ) ;
#line 172
extern wint_t putwchar(wchar_t  ) ;
#line 174
extern int fwide(FILE * , int  ) ;
#line 47 "/usr/include/inttypes.h"
extern intmax_t strtoimax(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 49
extern uintmax_t strtoumax(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 51
extern intmax_t wcstoimax(wchar_t const   * __restrict   , wchar_t ** __restrict   ,
                          int  ) ;
#line 53
extern uintmax_t wcstoumax(wchar_t const   * __restrict   , wchar_t ** __restrict   ,
                           int  ) ;
#line 38 "tl2/tmalloc.h"
extern void *tmalloc_reserve(size_t size ) ;
#line 46
extern void tmalloc_release(void *dataPtr ) ;
#line 55
extern tmalloc_t *tmalloc_alloc(long initCapacity ) ;
#line 63
extern void tmalloc_free(tmalloc_t *tmallocPtr ) ;
#line 73
extern long tmalloc_append(tmalloc_t *tmallocPtr , void *dataPtr ) ;
#line 81
extern void tmalloc_clear(tmalloc_t *tmallocPtr ) ;
#line 91
extern void tmalloc_releaseAllForward(tmalloc_t *tmallocPtr , void (*visit)(void * ,
                                                                            size_t  ) ) ;
#line 101
extern void tmalloc_releaseAllReverse(tmalloc_t *tmallocPtr , void (*visit)(void * ,
                                                                            size_t  ) ) ;
#line 144 "tl2/tl2.h"
extern void TxStart(Thread * , sigjmp_buf * , int * ) ;
#line 146
extern Thread *TxNewThread() ;
#line 152
extern void TxFreeThread(Thread * ) ;
#line 153
extern void TxInitThread(Thread * , long id ) ;
#line 154
extern int TxCommit(Thread * ) ;
#line 155
extern void TxAbort(Thread * ) ;
#line 156
extern __intptr_t TxLoad(Thread * , __intptr_t volatile   * ) ;
#line 157
extern void TxStore(Thread * , __intptr_t volatile   * , __intptr_t  ) ;
#line 158
extern void TxStoreLocal(Thread * , __intptr_t volatile   * , __intptr_t  ) ;
#line 159
extern void TxOnce() ;
#line 160
extern void TxShutdown() ;
#line 162
extern void *TxAlloc(Thread * , size_t  ) ;
#line 163
extern void TxFree(Thread * , void * ) ;
#line 26 "port.h"
extern __intptr_t cmpxchg(__intptr_t volatile   * , __intptr_t  , __intptr_t  ) ;
#line 27
extern __intptr_t fetch_and_add1(__intptr_t volatile   * ) ;
#line 28
extern __intptr_t fetch_and_sub1(__intptr_t volatile   * ) ;
#line 37 "al.h"
extern int al_pthread_create(pthread_t * , pthread_attr_t const   * , void *(*)(void * ) ,
                             void * ) ;
#line 40
extern pthread_key_t _al_key ;
#line 41
extern int setAdaptMode(int  ) ;
#line 42
extern double setTransactOvhd(double  ) ;
#line 43
extern int transactMode(profile_t * ) ;
#line 44
extern void busy(void) ;
#line 45
extern void TxStoreSized(Thread * , __intptr_t * , __intptr_t * , size_t  ) ;
#line 46
extern void TxLoadSized(Thread * , __intptr_t * , __intptr_t * , size_t  ) ;
#line 47
extern void dump_profile(profile_t * ) ;
#line 9 "alx.h"
static int default_spins  =    100;
#line 8 "test2.c"
void help(void) 
{ 

  {
#line 11
  fprintf((FILE * __restrict  )(& __sF[2]), (char const   * __restrict  )"usage: test [-hnpx]\n  -p  number of threads (default: 2)\n  -n  number of repeats (default: 100)\n  -l  use lock only\n  -t  use transaction only\n  -x  transactional overhead (default: 25)\n  -h  show this\n");
#line 19
  exit(0);
}
}
#line 22 "test2.c"
struct head tab  =    {(struct list_entry *)((void *)0)};
#line 30 "test2.c"
profile_t _l1_prof  ;
#line 30 "test2.c"
void __attribute__((__constructor__))  _init_add(void) 
{ 

  {
#line 30
  _l1_prof.name = "_l1_prof";
}
}
#line 30 "test2.c"
void __attribute__((__destructor__))  _atexit_add(void) 
{ 

  {
#line 30
  dump_profile(& _l1_prof);
}
}
#line 30 "test2.c"
void _raw_add(long n ) 
{ struct list_entry *p ;
  struct list_entry *q ;
  struct list_entry *r ;
  void *tmp ;

  {
#line 36
  tmp = tmalloc_reserve(sizeof(*r));
#line 36
  r = (struct list_entry *)tmp;
#line 36
  if (! r) {
#line 36
    __assert13("test2.c", 36, "add", "(r = (struct list_entry*)malloc(sizeof(*r)))");
  }
#line 37
  r->key = n;
#line 38
  r->val = n + 1L;
#line 39
  q = (struct list_entry *)0;
#line 40
  p = tab.lh_first;
#line 40
  while (p) {
#line 41
    if (n == p->key) {
#line 42
      tmalloc_release((void *)r);
#line 43
      break;
    }
#line 45
    if (n < p->key) {
#line 46
      while (1) {
#line 46
        r->links.le_prev = p->links.le_prev;
#line 46
        r->links.le_next = p;
#line 46
        *(p->links.le_prev) = r;
#line 46
        p->links.le_prev = & r->links.le_next;
#line 46
        break;
      }
#line 47
      break;
    }
#line 49
    q = p;
#line 40
    p = p->links.le_next;
  }
#line 51
  if ((unsigned int )p == (unsigned int )((struct list_entry *)0)) {
#line 52
    if ((unsigned int )q == (unsigned int )((struct list_entry *)0)) {
#line 53
      while (1) {
#line 53
        r->links.le_next = tab.lh_first;
#line 53
        if ((unsigned int )r->links.le_next != (unsigned int )((void *)0)) {
#line 53
          (tab.lh_first)->links.le_prev = & r->links.le_next;
        }
#line 53
        tab.lh_first = r;
#line 53
        r->links.le_prev = & tab.lh_first;
#line 53
        break;
      }
    } else {
#line 55
      while (1) {
#line 55
        r->links.le_next = q->links.le_next;
#line 55
        if ((unsigned int )r->links.le_next != (unsigned int )((void *)0)) {
#line 55
          (q->links.le_next)->links.le_prev = & r->links.le_next;
        }
#line 55
        q->links.le_next = r;
#line 55
        r->links.le_prev = & q->links.le_next;
#line 55
        break;
      }
    }
  }
#line 57
  return;
}
}
#line 30 "test2.c"
void _stm_add(Thread *self , long n ) 
{ struct list_entry *p ;
  struct list_entry *q ;
  struct list_entry *r ;
  void *tmp ;
  long tmp7 ;
  long tmp8 ;
  struct list_entry *var9 ;
  long mem10 ;
  long mem11 ;
  struct list_entry **tmp12 ;
  struct list_entry **mem13 ;
  struct list_entry *tmp14 ;
  struct list_entry *tmp15 ;
  struct list_entry **mem16 ;
  struct list_entry **tmp17 ;
  struct list_entry *mem18 ;
  struct list_entry *tmp19 ;
  struct list_entry *var20 ;
  struct list_entry *mem21 ;
  struct list_entry **tmp22 ;
  struct list_entry *var23 ;
  struct list_entry *tmp24 ;
  struct list_entry **tmp25 ;
  struct list_entry *tmp26 ;
  struct list_entry *mem27 ;
  struct list_entry *mem28 ;
  struct list_entry **tmp29 ;
  struct list_entry *mem30 ;
  struct list_entry *tmp31 ;
  struct list_entry **tmp32 ;

  {
#line 36
  tmp = TxAlloc(self, sizeof(*r));
#line 36
  r = (struct list_entry *)tmp;
#line 36
  if (! r) {
#line 36
    __assert13("test2.c", 36, "add", "(r = (struct list_entry*)malloc(sizeof(*r)))");
  }
#line 37
  tmp7 = n;
#line 37
  TxStoreSized(self, (intptr_t *)(& r->key), (intptr_t *)(& tmp7), sizeof(long ));
#line 38
  tmp8 = n + 1L;
#line 38
  TxStoreSized(self, (intptr_t *)(& r->val), (intptr_t *)(& tmp8), sizeof(long ));
#line 39
  q = (struct list_entry *)0;
#line 22
  TxLoadSized(self, (intptr_t *)(& var9), (intptr_t *)(& tab.lh_first), sizeof(struct list_entry *));
#line 40
  p = var9;
#line 40
  while (p) {
    {
    TxLoadSized(self, (intptr_t *)(& mem10), (intptr_t *)(& p->key), sizeof(long ));
#line 41
    if (n == mem10) {
#line 42
      TxFree(self, (void *)r);
#line 43
      break;
    }
    }
    {
    TxLoadSized(self, (intptr_t *)(& mem11), (intptr_t *)(& p->key), sizeof(long ));
#line 45
    if (n < mem11) {
#line 46
      while (1) {
        TxLoadSized(self, (intptr_t *)(& mem13), (intptr_t *)(& p->links.le_prev),
                    sizeof(struct list_entry **));
#line 46
        tmp12 = mem13;
#line 46
        TxStoreSized(self, (intptr_t *)(& r->links.le_prev), (intptr_t *)(& tmp12),
                     sizeof(struct list_entry **));
#line 46
        tmp14 = p;
#line 46
        TxStoreSized(self, (intptr_t *)(& r->links.le_next), (intptr_t *)(& tmp14),
                     sizeof(struct list_entry *));
        TxLoadSized(self, (intptr_t *)(& mem16), (intptr_t *)(& p->links.le_prev),
                    sizeof(struct list_entry **));
#line 46
        tmp15 = r;
#line 46
        TxStoreSized(self, (intptr_t *)mem16, (intptr_t *)(& tmp15), sizeof(struct list_entry *));
#line 46
        tmp17 = & r->links.le_next;
#line 46
        TxStoreSized(self, (intptr_t *)(& p->links.le_prev), (intptr_t *)(& tmp17),
                     sizeof(struct list_entry **));
#line 46
        break;
      }
#line 47
      break;
    }
    }
#line 49
    q = p;
    TxLoadSized(self, (intptr_t *)(& mem18), (intptr_t *)(& p->links.le_next), sizeof(struct list_entry *));
#line 40
    p = mem18;
  }
#line 51
  if ((unsigned int )p == (unsigned int )((struct list_entry *)0)) {
#line 52
    if ((unsigned int )q == (unsigned int )((struct list_entry *)0)) {
#line 53
      while (1) {
#line 22
        TxLoadSized(self, (intptr_t *)(& var20), (intptr_t *)(& tab.lh_first), sizeof(struct list_entry *));
#line 53
        tmp19 = var20;
#line 53
        TxStoreSized(self, (intptr_t *)(& r->links.le_next), (intptr_t *)(& tmp19),
                     sizeof(struct list_entry *));
        {
        TxLoadSized(self, (intptr_t *)(& mem21), (intptr_t *)(& r->links.le_next),
                    sizeof(struct list_entry *));
#line 53
        if ((unsigned int )mem21 != (unsigned int )((void *)0)) {
#line 22
          TxLoadSized(self, (intptr_t *)(& var23), (intptr_t *)(& tab.lh_first), sizeof(struct list_entry *));
#line 53
          tmp22 = & r->links.le_next;
#line 53
          TxStoreSized(self, (intptr_t *)(& var23->links.le_prev), (intptr_t *)(& tmp22),
                       sizeof(struct list_entry **));
        }
        }
#line 53
        tmp24 = r;
#line 53
        TxStoreSized(self, (intptr_t *)(& tab.lh_first), (intptr_t *)(& tmp24), sizeof(struct list_entry *));
#line 53
        tmp25 = & tab.lh_first;
#line 53
        TxStoreSized(self, (intptr_t *)(& r->links.le_prev), (intptr_t *)(& tmp25),
                     sizeof(struct list_entry **));
#line 53
        break;
      }
    } else {
#line 55
      while (1) {
        TxLoadSized(self, (intptr_t *)(& mem27), (intptr_t *)(& q->links.le_next),
                    sizeof(struct list_entry *));
#line 55
        tmp26 = mem27;
#line 55
        TxStoreSized(self, (intptr_t *)(& r->links.le_next), (intptr_t *)(& tmp26),
                     sizeof(struct list_entry *));
        {
        TxLoadSized(self, (intptr_t *)(& mem28), (intptr_t *)(& r->links.le_next),
                    sizeof(struct list_entry *));
#line 55
        if ((unsigned int )mem28 != (unsigned int )((void *)0)) {
          TxLoadSized(self, (intptr_t *)(& mem30), (intptr_t *)(& q->links.le_next),
                      sizeof(struct list_entry *));
#line 55
          tmp29 = & r->links.le_next;
#line 55
          TxStoreSized(self, (intptr_t *)(& mem30->links.le_prev), (intptr_t *)(& tmp29),
                       sizeof(struct list_entry **));
        }
        }
#line 55
        tmp31 = r;
#line 55
        TxStoreSized(self, (intptr_t *)(& q->links.le_next), (intptr_t *)(& tmp31),
                     sizeof(struct list_entry *));
#line 55
        tmp32 = & q->links.le_next;
#line 55
        TxStoreSized(self, (intptr_t *)(& r->links.le_prev), (intptr_t *)(& tmp32),
                     sizeof(struct list_entry **));
#line 55
        break;
      }
    }
  }
#line 57
  return;
}
}
#line 30 "test2.c"
static void add(long n ) 
{ profile_t *prof ;
  void *(*rawfunc)(void) ;
  void *(*stmfunc)(Thread * ) ;
  int ro ;
  int cnt ;
  thread_t *self ;
  nest_t *nest ;
  nest_t *nested ;
  __intptr_t tmp ;
  sigjmp_buf buf ;
  void *tmp___0 ;
  void *tmp___1 ;
  __intptr_t tmp___2 ;
  int tmp___3 ;
  __intptr_t tmp___4 ;
  __intptr_t tmp___5 ;
  int tmp___6 ;

  {
#line 14 "alx.h"
  prof = & _l1_prof;
#line 15
  rawfunc = (void *(*)(void))0;
#line 16
  stmfunc = (void *(*)(Thread * ))0;
#line 17
  ro = 0;
#line 18
  cnt = default_spins;
#line 25
  tmp___0 = pthread_getspecific(_al_key);
#line 25
  self = (thread_t *)tmp___0;
#line 25
  if (! self) {
#line 25
    __assert13("alx.h", 25, "_al_template", "(self = pthread_getspecific(_al_key))");
  }
#line 26
  nest = self->prof_list.slh_first;
#line 26
  while (nest) {
#line 27
    if ((unsigned int )nest->prof == (unsigned int )prof) {
#line 27
      break;
    }
#line 26
    nest = nest->next.sle_next;
  }
#line 29
  if ((unsigned int )nest == (unsigned int )((nest_t *)0)) {
#line 30
    tmp___1 = malloc(sizeof(*nest));
#line 30
    nest = (nest_t *)tmp___1;
#line 30
    if (! nest) {
#line 30
      __assert13("alx.h", 30, "_al_template", "nest = malloc(sizeof(*nest))");
    }
#line 31
    nest->prof = prof;
#line 32
    nest->level = 0L;
#line 33
    while (1) {
#line 33
      nest->next.sle_next = self->prof_list.slh_first;
#line 33
      self->prof_list.slh_first = nest;
#line 33
      break;
    }
  }
#line 35
  nested = self->prof_list.slh_first;
#line 35
  while (nested) {
#line 36
    if (0L < nested->level) {
#line 36
      break;
    }
#line 35
    nested = nested->next.sle_next;
  }
#line 38
  if ((unsigned int )nested != (unsigned int )((nest_t *)0)) {
    goto _L___0;
  } else {
#line 38
    if (nest->level == 0L) {
#line 38
      tmp___6 = transactMode(prof);
#line 38
      if (tmp___6) {
        _L___0: /* CIL Label */ 
#line 39
        if (! (0L <= nest->level)) {
#line 39
          __assert13("alx.h", 39, "_al_template", "0 <= nest->level");
        }
#line 40
        if ((unsigned int )nested != (unsigned int )((nest_t *)0)) {
#line 41
          _stm_add(self->stmThread, n);
        } else {
#line 43
          fetch_and_add1(& prof->threadsWaiting);
#line 44
          while (1) {
#line 44
            tmp = (int )prof->lockHeld;
#line 44
            if (! (tmp == -1)) {
#line 44
              tmp___2 = cmpxchg(& prof->lockHeld, tmp, tmp + 1);
#line 44
              if (! (tmp___2 != tmp)) {
#line 44
                break;
              }
            }
#line 46
            cnt --;
#line 46
            if (cnt <= 0) {
#line 47
              busy();
#line 47
              cnt = default_spins;
            }
          }
#line 50
          fetch_and_sub1(& prof->threadsWaiting);
#line 51
          tmp___3 = sigsetjmp((long *)(buf), 1);
#line 51
          if (tmp___3) {
#line 51
            nest->level = 0L;
          }
#line 52
          fetch_and_add1((__intptr_t volatile   *)(& nest->level));
#line 53
          fetch_and_add1(& prof->tries);
#line 54
          __asm__  volatile   ("": : : "memory");
#line 55
          TxStart(self->stmThread, & buf, & ro);
#line 56
          _stm_add(self->stmThread, n);
#line 57
          TxCommit(self->stmThread);
#line 58
          fetch_and_add1(& prof->commit);
#line 59
          fetch_and_sub1((__intptr_t volatile   *)(& nest->level));
#line 60
          fetch_and_sub1(& prof->lockHeld);
        }
      } else {
        goto _L___1;
      }
    } else {
      _L___1: /* CIL Label */ 
#line 63
      if (! (nest->level <= 0L)) {
#line 63
        __assert13("alx.h", 63, "_al_template", "nest->level <= 0");
      }
#line 64
      if (nest->level < 0L) {
#line 65
        _raw_add(n);
      } else {
#line 67
        fetch_and_add1(& prof->invokeInLockMode);
#line 68
        fetch_and_add1(& prof->threadsWaiting);
#line 69
        if (prof->lockHeld != (__intptr_t volatile   )0) {
          goto _L;
        } else {
#line 69
          tmp___5 = cmpxchg(& prof->lockHeld, 0, ~ 0);
#line 69
          if (tmp___5 != 0) {
            _L: /* CIL Label */ 
#line 71
            fetch_and_add1(& prof->waitLock);
#line 72
            while (1) {
#line 72
              if (! (prof->lockHeld != (__intptr_t volatile   )0)) {
#line 72
                tmp___4 = cmpxchg(& prof->lockHeld, 0, ~ 0);
#line 72
                if (! (tmp___4 != 0)) {
#line 72
                  break;
                }
              }
#line 74
              cnt --;
#line 74
              if (cnt <= 0) {
#line 75
                busy();
#line 75
                cnt = default_spins;
              }
            }
          }
        }
#line 78
        fetch_and_sub1(& prof->threadsWaiting);
#line 79
        nest->level = -1L;
#line 80
        _raw_add(n);
#line 81
        nest->level = 0L;
#line 82
        fetch_and_add1(& prof->lockHeld);
      }
    }
  }
#line 85
  return;
}
}
#line 60 "test2.c"
int _raw_del(long n ) 
{ struct list_entry *p ;

  {
#line 66
  p = tab.lh_first;
#line 66
  while (p) {
#line 67
    if (n == p->key) {
#line 68
      while (1) {
#line 68
        if ((unsigned int )p->links.le_next != (unsigned int )((void *)0)) {
#line 68
          (p->links.le_next)->links.le_prev = p->links.le_prev;
        }
#line 68
        *(p->links.le_prev) = p->links.le_next;
#line 68
        break;
      }
#line 69
      tmalloc_release((void *)p);
#line 70
      return ((int )1);
    }
#line 66
    p = p->links.le_next;
  }
#line 73
  return ((int )0);
}
}
#line 60 "test2.c"
int _stm_del(Thread *self , long n ) 
{ struct list_entry *p ;
  struct list_entry *var4 ;
  long mem5 ;
  struct list_entry *mem6 ;
  struct list_entry **tmp7 ;
  struct list_entry **mem8 ;
  struct list_entry *mem9 ;
  struct list_entry *tmp10 ;
  struct list_entry *mem11 ;
  struct list_entry **mem12 ;
  struct list_entry *mem13 ;

  {
#line 22
  TxLoadSized(self, (intptr_t *)(& var4), (intptr_t *)(& tab.lh_first), sizeof(struct list_entry *));
#line 66
  p = var4;
#line 66
  while (p) {
    {
    TxLoadSized(self, (intptr_t *)(& mem5), (intptr_t *)(& p->key), sizeof(long ));
#line 67
    if (n == mem5) {
#line 68
      while (1) {
        {
        TxLoadSized(self, (intptr_t *)(& mem6), (intptr_t *)(& p->links.le_next),
                    sizeof(struct list_entry *));
#line 68
        if ((unsigned int )mem6 != (unsigned int )((void *)0)) {
          TxLoadSized(self, (intptr_t *)(& mem8), (intptr_t *)(& p->links.le_prev),
                      sizeof(struct list_entry **));
          TxLoadSized(self, (intptr_t *)(& mem9), (intptr_t *)(& p->links.le_next),
                      sizeof(struct list_entry *));
#line 68
          tmp7 = mem8;
#line 68
          TxStoreSized(self, (intptr_t *)(& mem9->links.le_prev), (intptr_t *)(& tmp7),
                       sizeof(struct list_entry **));
        }
        }
        TxLoadSized(self, (intptr_t *)(& mem11), (intptr_t *)(& p->links.le_next),
                    sizeof(struct list_entry *));
        TxLoadSized(self, (intptr_t *)(& mem12), (intptr_t *)(& p->links.le_prev),
                    sizeof(struct list_entry **));
#line 68
        tmp10 = mem11;
#line 68
        TxStoreSized(self, (intptr_t *)mem12, (intptr_t *)(& tmp10), sizeof(struct list_entry *));
#line 68
        break;
      }
#line 69
      TxFree(self, (void *)p);
#line 70
      return ((int )1);
    }
    }
    TxLoadSized(self, (intptr_t *)(& mem13), (intptr_t *)(& p->links.le_next), sizeof(struct list_entry *));
#line 66
    p = mem13;
  }
#line 73
  return ((int )0);
}
}
#line 60 "test2.c"
static int del(long n ) 
{ profile_t *prof ;
  void *(*rawfunc)(void) ;
  void *(*stmfunc)(Thread * ) ;
  int ro ;
  int cnt ;
  thread_t *self ;
  nest_t *nest ;
  nest_t *nested ;
  __intptr_t tmp ;
  sigjmp_buf buf ;
  void *tmp___0 ;
  void *tmp___1 ;
  __intptr_t tmp___2 ;
  int tmp___3 ;
  __intptr_t tmp___4 ;
  __intptr_t tmp___5 ;
  int tmp___6 ;
  int tmp18 ;

  {
#line 14 "alx.h"
  prof = & _l1_prof;
#line 15
  rawfunc = (void *(*)(void))0;
#line 16
  stmfunc = (void *(*)(Thread * ))0;
#line 17
  ro = 0;
#line 18
  cnt = default_spins;
#line 25
  tmp___0 = pthread_getspecific(_al_key);
#line 25
  self = (thread_t *)tmp___0;
#line 25
  if (! self) {
#line 25
    __assert13("alx.h", 25, "_al_template", "(self = pthread_getspecific(_al_key))");
  }
#line 26
  nest = self->prof_list.slh_first;
#line 26
  while (nest) {
#line 27
    if ((unsigned int )nest->prof == (unsigned int )prof) {
#line 27
      break;
    }
#line 26
    nest = nest->next.sle_next;
  }
#line 29
  if ((unsigned int )nest == (unsigned int )((nest_t *)0)) {
#line 30
    tmp___1 = malloc(sizeof(*nest));
#line 30
    nest = (nest_t *)tmp___1;
#line 30
    if (! nest) {
#line 30
      __assert13("alx.h", 30, "_al_template", "nest = malloc(sizeof(*nest))");
    }
#line 31
    nest->prof = prof;
#line 32
    nest->level = 0L;
#line 33
    while (1) {
#line 33
      nest->next.sle_next = self->prof_list.slh_first;
#line 33
      self->prof_list.slh_first = nest;
#line 33
      break;
    }
  }
#line 35
  nested = self->prof_list.slh_first;
#line 35
  while (nested) {
#line 36
    if (0L < nested->level) {
#line 36
      break;
    }
#line 35
    nested = nested->next.sle_next;
  }
#line 38
  if ((unsigned int )nested != (unsigned int )((nest_t *)0)) {
    goto _L___0;
  } else {
#line 38
    if (nest->level == 0L) {
#line 38
      tmp___6 = transactMode(prof);
#line 38
      if (tmp___6) {
        _L___0: /* CIL Label */ 
#line 39
        if (! (0L <= nest->level)) {
#line 39
          __assert13("alx.h", 39, "_al_template", "0 <= nest->level");
        }
#line 40
        if ((unsigned int )nested != (unsigned int )((nest_t *)0)) {
#line 41
          tmp18 = _stm_del(self->stmThread, n);
        } else {
#line 43
          fetch_and_add1(& prof->threadsWaiting);
#line 44
          while (1) {
#line 44
            tmp = (int )prof->lockHeld;
#line 44
            if (! (tmp == -1)) {
#line 44
              tmp___2 = cmpxchg(& prof->lockHeld, tmp, tmp + 1);
#line 44
              if (! (tmp___2 != tmp)) {
#line 44
                break;
              }
            }
#line 46
            cnt --;
#line 46
            if (cnt <= 0) {
#line 47
              busy();
#line 47
              cnt = default_spins;
            }
          }
#line 50
          fetch_and_sub1(& prof->threadsWaiting);
#line 51
          tmp___3 = sigsetjmp((long *)(buf), 1);
#line 51
          if (tmp___3) {
#line 51
            nest->level = 0L;
          }
#line 52
          fetch_and_add1((__intptr_t volatile   *)(& nest->level));
#line 53
          fetch_and_add1(& prof->tries);
#line 54
          __asm__  volatile   ("": : : "memory");
#line 55
          TxStart(self->stmThread, & buf, & ro);
#line 56
          tmp18 = _stm_del(self->stmThread, n);
#line 57
          TxCommit(self->stmThread);
#line 58
          fetch_and_add1(& prof->commit);
#line 59
          fetch_and_sub1((__intptr_t volatile   *)(& nest->level));
#line 60
          fetch_and_sub1(& prof->lockHeld);
        }
      } else {
        goto _L___1;
      }
    } else {
      _L___1: /* CIL Label */ 
#line 63
      if (! (nest->level <= 0L)) {
#line 63
        __assert13("alx.h", 63, "_al_template", "nest->level <= 0");
      }
#line 64
      if (nest->level < 0L) {
#line 65
        tmp18 = _raw_del(n);
      } else {
#line 67
        fetch_and_add1(& prof->invokeInLockMode);
#line 68
        fetch_and_add1(& prof->threadsWaiting);
#line 69
        if (prof->lockHeld != (__intptr_t volatile   )0) {
          goto _L;
        } else {
#line 69
          tmp___5 = cmpxchg(& prof->lockHeld, 0, ~ 0);
#line 69
          if (tmp___5 != 0) {
            _L: /* CIL Label */ 
#line 71
            fetch_and_add1(& prof->waitLock);
#line 72
            while (1) {
#line 72
              if (! (prof->lockHeld != (__intptr_t volatile   )0)) {
#line 72
                tmp___4 = cmpxchg(& prof->lockHeld, 0, ~ 0);
#line 72
                if (! (tmp___4 != 0)) {
#line 72
                  break;
                }
              }
#line 74
              cnt --;
#line 74
              if (cnt <= 0) {
#line 75
                busy();
#line 75
                cnt = default_spins;
              }
            }
          }
        }
#line 78
        fetch_and_sub1(& prof->threadsWaiting);
#line 79
        nest->level = -1L;
#line 80
        tmp18 = _raw_del(n);
#line 81
        nest->level = 0L;
#line 82
        fetch_and_add1(& prof->lockHeld);
      }
    }
  }
#line 85
  return (tmp18);
}
}
#line 76 "test2.c"
int _raw_lookup(long n , struct list_entry *ret ) 
{ struct list_entry *p ;

  {
#line 82
  p = tab.lh_first;
#line 82
  while (p) {
#line 83
    if (n == p->key) {
#line 84
      memcpy((void * __restrict  )ret, (void const   * __restrict  )p, sizeof(*p));
#line 85
      return ((int )1);
    }
#line 82
    p = p->links.le_next;
  }
#line 88
  return ((int )0);
}
}
#line 76 "test2.c"
int _stm_lookup(Thread *self , long n , struct list_entry *ret ) 
{ struct list_entry *p ;
  struct list_entry *var5 ;
  long mem6 ;
  struct list_entry *mem7 ;

  {
#line 22
  TxLoadSized(self, (intptr_t *)(& var5), (intptr_t *)(& tab.lh_first), sizeof(struct list_entry *));
#line 82
  p = var5;
#line 82
  while (p) {
    {
    TxLoadSized(self, (intptr_t *)(& mem6), (intptr_t *)(& p->key), sizeof(long ));
#line 83
    if (n == mem6) {
#line 84
      memcpy((void * __restrict  )ret, (void const   * __restrict  )p, sizeof(*p));
#line 85
      return ((int )1);
    }
    }
    TxLoadSized(self, (intptr_t *)(& mem7), (intptr_t *)(& p->links.le_next), sizeof(struct list_entry *));
#line 82
    p = mem7;
  }
#line 88
  return ((int )0);
}
}
#line 76 "test2.c"
static int lookup(long n , struct list_entry *ret ) 
{ profile_t *prof ;
  void *(*rawfunc)(void) ;
  void *(*stmfunc)(Thread * ) ;
  int ro ;
  int cnt ;
  thread_t *self ;
  nest_t *nest ;
  nest_t *nested ;
  __intptr_t tmp ;
  sigjmp_buf buf ;
  void *tmp___0 ;
  void *tmp___1 ;
  __intptr_t tmp___2 ;
  int tmp___3 ;
  __intptr_t tmp___4 ;
  __intptr_t tmp___5 ;
  int tmp___6 ;
  int tmp18 ;

  {
#line 14 "alx.h"
  prof = & _l1_prof;
#line 15
  rawfunc = (void *(*)(void))0;
#line 16
  stmfunc = (void *(*)(Thread * ))0;
#line 17
  ro = 1;
#line 18
  cnt = default_spins;
#line 25
  tmp___0 = pthread_getspecific(_al_key);
#line 25
  self = (thread_t *)tmp___0;
#line 25
  if (! self) {
#line 25
    __assert13("alx.h", 25, "_al_template", "(self = pthread_getspecific(_al_key))");
  }
#line 26
  nest = self->prof_list.slh_first;
#line 26
  while (nest) {
#line 27
    if ((unsigned int )nest->prof == (unsigned int )prof) {
#line 27
      break;
    }
#line 26
    nest = nest->next.sle_next;
  }
#line 29
  if ((unsigned int )nest == (unsigned int )((nest_t *)0)) {
#line 30
    tmp___1 = malloc(sizeof(*nest));
#line 30
    nest = (nest_t *)tmp___1;
#line 30
    if (! nest) {
#line 30
      __assert13("alx.h", 30, "_al_template", "nest = malloc(sizeof(*nest))");
    }
#line 31
    nest->prof = prof;
#line 32
    nest->level = 0L;
#line 33
    while (1) {
#line 33
      nest->next.sle_next = self->prof_list.slh_first;
#line 33
      self->prof_list.slh_first = nest;
#line 33
      break;
    }
  }
#line 35
  nested = self->prof_list.slh_first;
#line 35
  while (nested) {
#line 36
    if (0L < nested->level) {
#line 36
      break;
    }
#line 35
    nested = nested->next.sle_next;
  }
#line 38
  if ((unsigned int )nested != (unsigned int )((nest_t *)0)) {
    goto _L___0;
  } else {
#line 38
    if (nest->level == 0L) {
#line 38
      tmp___6 = transactMode(prof);
#line 38
      if (tmp___6) {
        _L___0: /* CIL Label */ 
#line 39
        if (! (0L <= nest->level)) {
#line 39
          __assert13("alx.h", 39, "_al_template", "0 <= nest->level");
        }
#line 40
        if ((unsigned int )nested != (unsigned int )((nest_t *)0)) {
#line 41
          tmp18 = _stm_lookup(self->stmThread, n, ret);
        } else {
#line 43
          fetch_and_add1(& prof->threadsWaiting);
#line 44
          while (1) {
#line 44
            tmp = (int )prof->lockHeld;
#line 44
            if (! (tmp == -1)) {
#line 44
              tmp___2 = cmpxchg(& prof->lockHeld, tmp, tmp + 1);
#line 44
              if (! (tmp___2 != tmp)) {
#line 44
                break;
              }
            }
#line 46
            cnt --;
#line 46
            if (cnt <= 0) {
#line 47
              busy();
#line 47
              cnt = default_spins;
            }
          }
#line 50
          fetch_and_sub1(& prof->threadsWaiting);
#line 51
          tmp___3 = sigsetjmp((long *)(buf), 1);
#line 51
          if (tmp___3) {
#line 51
            nest->level = 0L;
          }
#line 52
          fetch_and_add1((__intptr_t volatile   *)(& nest->level));
#line 53
          fetch_and_add1(& prof->tries);
#line 54
          __asm__  volatile   ("": : : "memory");
#line 55
          TxStart(self->stmThread, & buf, & ro);
#line 56
          tmp18 = _stm_lookup(self->stmThread, n, ret);
#line 57
          TxCommit(self->stmThread);
#line 58
          fetch_and_add1(& prof->commit);
#line 59
          fetch_and_sub1((__intptr_t volatile   *)(& nest->level));
#line 60
          fetch_and_sub1(& prof->lockHeld);
        }
      } else {
        goto _L___1;
      }
    } else {
      _L___1: /* CIL Label */ 
#line 63
      if (! (nest->level <= 0L)) {
#line 63
        __assert13("alx.h", 63, "_al_template", "nest->level <= 0");
      }
#line 64
      if (nest->level < 0L) {
#line 65
        tmp18 = _raw_lookup(n, ret);
      } else {
#line 67
        fetch_and_add1(& prof->invokeInLockMode);
#line 68
        fetch_and_add1(& prof->threadsWaiting);
#line 69
        if (prof->lockHeld != (__intptr_t volatile   )0) {
          goto _L;
        } else {
#line 69
          tmp___5 = cmpxchg(& prof->lockHeld, 0, ~ 0);
#line 69
          if (tmp___5 != 0) {
            _L: /* CIL Label */ 
#line 71
            fetch_and_add1(& prof->waitLock);
#line 72
            while (1) {
#line 72
              if (! (prof->lockHeld != (__intptr_t volatile   )0)) {
#line 72
                tmp___4 = cmpxchg(& prof->lockHeld, 0, ~ 0);
#line 72
                if (! (tmp___4 != 0)) {
#line 72
                  break;
                }
              }
#line 74
              cnt --;
#line 74
              if (cnt <= 0) {
#line 75
                busy();
#line 75
                cnt = default_spins;
              }
            }
          }
        }
#line 78
        fetch_and_sub1(& prof->threadsWaiting);
#line 79
        nest->level = -1L;
#line 80
        tmp18 = _raw_lookup(n, ret);
#line 81
        nest->level = 0L;
#line 82
        fetch_and_add1(& prof->lockHeld);
      }
    }
  }
#line 85
  return (tmp18);
}
}
#line 91 "test2.c"
void *task(void *arg ) 
{ long n ;
  long t ;
  struct list_entry ret ;
  long tmp ;
  long tmp___0 ;

  {
#line 94
  n = (long )((int )arg);
#line 98
  while (1) {
#line 98
    tmp___0 = n;
#line 98
    n --;
#line 98
    if (! tmp___0) {
#line 98
      break;
    }
#line 99
    tmp = random();
#line 99
    t = tmp % 1000L;
#line 100
    switch ((int )(n % 4L)) {
    case 0: 
#line 101
    add(t);
#line 101
    break;
    case 1: 
#line 102
    del(t);
#line 102
    break;
    default: 
#line 103
    lookup(t, & ret);
#line 103
    break;
    }
  }
#line 106
  return ((void *)0);
}
}
#line 109 "test2.c"
int main(int argc , char **argv ) 
{ int p ;
  int n ;
  int ch ;
  int i ;
  pthread_t t[256] ;
  void *r ;
  double tmp ;
  struct list_entry *p___0 ;
  long a ;
  long b ;
  long c ;

  {
#line 112
  p = 2;
#line 112
  n = 100;
#line 116
  while (1) {
#line 116
    ch = getopt(argc, (char * const  *)argv, "p:n:ltx:");
#line 116
    if (! (ch != -1)) {
#line 116
      break;
    }
#line 117
    switch (ch) {
    case 110: 
#line 118
    n = atoi((char const   *)optarg);
#line 118
    break;
    case 112: 
#line 119
    p = atoi((char const   *)optarg);
#line 119
    break;
    case 108: 
#line 120
    setAdaptMode(-1);
#line 120
    break;
    case 116: 
#line 121
    setAdaptMode(1);
#line 121
    break;
    case 120: 
#line 122
    tmp = atof((char const   *)optarg);
#line 122
    setTransactOvhd(tmp);
#line 122
    break;
    case 104: 
    default: 
#line 124
    help();
    }
  }
#line 127
  argc -= optind;
#line 128
  argv += optind;
#line 130
  if (256 <= p) {
#line 130
    p = 256;
  }
#line 131
  i = 0;
#line 131
  while (i < p) {
#line 131
    al_pthread_create(& t[i], (pthread_attr_t const   *)0, & task, (void *)n);
#line 131
    i ++;
  }
#line 132
  i = 0;
#line 132
  while (i < p) {
#line 132
    pthread_join(t[i], & r);
#line 132
    i ++;
  }
#line 135
  a = 0L;
#line 135
  b = 0L;
#line 135
  c = 0L;
#line 137
  p___0 = tab.lh_first;
#line 137
  while (p___0) {
#line 138
    b = p___0->key;
#line 139
    if (! (a <= b)) {
#line 139
      printf((char const   * __restrict  )"*** Oops, %ld <= %ld\n", a, b);
    }
#line 140
    a = b;
#line 140
    c ++;
#line 137
    p___0 = p___0->links.le_next;
  }
#line 142
  printf((char const   * __restrict  )"number of elements=%ld\n", c);
#line 144
  return (0);
}
}
